using Content.Shared._Frostheim.Shuttle;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Frostheim.Shuttle;

[GenerateTypedNameReferences]
public sealed partial class FrostheimStatusConsoleWindow : DefaultWindow
{
    private static readonly Color PanelBg = Color.FromHex("#0a0e14");
    private static readonly Color HeaderBg = Color.FromHex("#0f1a24");
    private static readonly Color HeaderText = Color.FromHex("#7a9ab0");

    private StatusDisplayControl? _display;

    public FrostheimStatusConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        MainPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = PanelBg,
            BorderColor = Color.FromHex("#1a2a3a"),
            BorderThickness = new Thickness(1),
        };

        HeaderPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = HeaderBg,
            BorderColor = Color.FromHex("#2a3a4a"),
            BorderThickness = new Thickness(0, 0, 0, 1),
        };

        HeaderLabel.FontColorOverride = HeaderText;

        _display = new StatusDisplayControl();
        StatusDisplay.AddChild(_display);
    }

    public void UpdateState(FrostheimStatusConsoleState state)
    {
        _display?.UpdateState(state);

        Title = state.Ready ? "SYS-STATUS :: ГОТОВ" : "SYS-STATUS :: ДИАГНОСТИКА";
    }
}
