using Content.Shared._Frostheim.Shuttle;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Frostheim.Shuttle;

[GenerateTypedNameReferences]
public sealed partial class FrostheimNavConsoleWindow : DefaultWindow
{
    public event Action<int, int>? OnPathClick;
    public event Action? OnResetPath;
    public event Action<int, float>? OnCalibrate;
    public event Action? OnConfirm;

    private NavGridControl? _gridControl;
    private NavCalibrationControl? _calibrationControl;

    private static readonly Color PanelBg = Color.FromHex("#0a0e14");
    private static readonly Color HeaderBg = Color.FromHex("#0f1a24");
    private static readonly Color StatusColor = Color.FromHex("#7a9ab0");
    private static readonly Color StatusCompleteColor = Color.FromHex("#2a8a2a");

    public FrostheimNavConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        var panelStyle = new StyleBoxFlat
        {
            BackgroundColor = PanelBg,
            BorderColor = Color.FromHex("#1a2a3a"),
            BorderThickness = new Thickness(1),
        };
        MainPanel.PanelOverride = panelStyle;

        var headerStyle = new StyleBoxFlat
        {
            BackgroundColor = HeaderBg,
            BorderColor = Color.FromHex("#2a3a4a"),
            BorderThickness = new Thickness(0, 0, 0, 1),
            ContentMarginLeftOverride = 8,
            ContentMarginRightOverride = 8,
        };
        HeaderPanel.PanelOverride = headerStyle;

        StatusLabel.FontColorOverride = StatusColor;

        ResetButton.OnPressed += _ => OnResetPath?.Invoke();
        ConfirmButton.OnPressed += _ => OnConfirm?.Invoke();
    }

    public void UpdateState(FrostheimNavConsoleState state)
    {
        switch (state.Phase)
        {
            case NavGamePhase.Pathfinding:
                Title = "NAV-SYS :: МАРШРУТ";
                StatusLabel.Text = "[ ЭТАП 1/2 ] ПРОКЛАДКА МАРШРУТА";
                StatusLabel.FontColorOverride = StatusColor;
                ResetButton.Visible = true;
                ConfirmButton.Disabled = !state.PathComplete;
                ShowGridControl(state);
                break;

            case NavGamePhase.Calibration:
                Title = "NAV-SYS :: КАЛИБРОВКА";
                StatusLabel.Text = "[ ЭТАП 2/2 ] КАЛИБРОВКА КООРДИНАТ";
                StatusLabel.FontColorOverride = StatusColor;
                ResetButton.Visible = false;
                UpdateCalibrationConfirm(state);
                ShowCalibrationControl(state);
                break;

            case NavGamePhase.Complete:
                Title = "NAV-SYS :: ONLINE";
                StatusLabel.Text = ">>> НАВИГАЦИЯ НАСТРОЕНА. КУРС ПРОЛОЖЕН. <<<";
                StatusLabel.FontColorOverride = StatusCompleteColor;
                ResetButton.Visible = false;
                ConfirmButton.Visible = false;
                GameContainer.RemoveAllChildren();
                break;
        }
    }

    private void ShowGridControl(FrostheimNavConsoleState state)
    {
        if (_gridControl == null)
        {
            GameContainer.RemoveAllChildren();
            _gridControl = new NavGridControl();
            _gridControl.OnCellClick += (x, y) => OnPathClick?.Invoke(x, y);
            GameContainer.AddChild(_gridControl);
            _calibrationControl = null;
        }

        _gridControl.UpdateState(state);
    }

    private void ShowCalibrationControl(FrostheimNavConsoleState state)
    {
        if (_calibrationControl == null)
        {
            GameContainer.RemoveAllChildren();
            _calibrationControl = new NavCalibrationControl();
            _calibrationControl.OnSliderChanged += (idx, val) => OnCalibrate?.Invoke(idx, val);
            GameContainer.AddChild(_calibrationControl);
            _gridControl = null;
        }

        _calibrationControl.UpdateState(state);
    }

    private void UpdateCalibrationConfirm(FrostheimNavConsoleState state)
    {
        var allGood = true;
        for (var i = 0; i < state.TargetValues.Length; i++)
        {
            if (Math.Abs(state.CurrentValues[i] - state.TargetValues[i]) > state.Tolerance)
            {
                allGood = false;
                break;
            }
        }

        ConfirmButton.Disabled = !allGood;
    }
}
