// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Shared.Body.Prototypes;
using Content.Shared.DeadSpace.Virus.Prototypes;
using Content.Shared.DeadSpace.Virus;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Client.UserInterface.Controls;
using Content.Client.DeadSpace.Virus.Systems;
using Range = Robust.Client.UserInterface.Controls.Range;
using Robust.Client.UserInterface;
using Robust.Shared.Input;
using Content.Shared.DeadSpace.Necromorphs.InfectionDead.Components;

namespace Content.Client.DeadSpace.Virus.UI;

[GenerateTypedNameReferences]
public sealed partial class VirusEvolutionConsoleWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private VirusEvolutionConsoleBoundUserInterfaceState? _lastUpdate;
    private readonly List<VirusSymptomPrototype> _availableSymptoms = new();
    private readonly List<BodyPrototype> _availableBodies = new();
    private ProtoId<VirusSymptomPrototype>? _selectedActiveSymptom;
    private ProtoId<BodyPrototype>? _selectedActiveBody;


    public VirusEvolutionConsoleWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        HpMulty.OnValueChanged += (args) => OnReleaseSliderChanged(args, HpMulty_Value);
        DamageMulty.OnValueChanged += (args) => OnReleaseSliderChanged(args, DamageMulty_Value);
        SpeedMulty.OnValueChanged += (args) => OnReleaseSliderChanged(args, SpeedMulty_Value);
        StaminaMulty.OnValueChanged += (args) => OnReleaseSliderChanged(args, StaminaMulty_Value);

        AvailableSymptomsList.OnItemSelected += OnAvailableSymptomSelected;
        AvailableBodiesList.OnItemSelected += OnAvailableBodySelected;

        ActiveSymptomsList.OnItemSelected += OnActiveSymptomSelected;
        ActiveBodiesList.OnItemSelected += OnActiveBodySelected;

        DeleteSymptomButton.Disabled = true;
        DeleteBodyButton.Disabled = true;
    }
    private void OnReleaseSliderChanged(Range range, Label label)
    {
        label.Text = range.Value.ToString();
        FinalPriceLabel.Text = $"Final Price: {(int)(1000 * (Math.Abs(HpMulty.Value - 1) + Math.Abs(DamageMulty.Value - 1) + Math.Abs(SpeedMulty.Value - 1) + Math.Abs(StaminaMulty.Value - 1)))}";
    }
    public void Populate(VirusEvolutionConsoleBoundUserInterfaceState state)
    {
        _lastUpdate = state;
        MutationPointsLabel.Text = Loc.GetString("virus-evolution-mutation-points", ("points", state.MutationPoints));
        WhitelistMutationPointsLabel.Text = Loc.GetString("virus-evolution-mutation-points", ("points", state.MutationPoints));
        // Статистика вируса
        if (!state.IsSentientVirus)
        {
            VirusHealthLabel.Visible = false;
            InfectivityLabel.Visible = false;
            InfectedCountLabel.Visible = false;
            PointsPerSecondLabel.Visible = false;
        }
        else
        {
            VirusHealthLabel.Text = Loc.GetString("virus-evolution-health", ("max", (int)state.MaxThreshold));
            InfectivityLabel.Text = Loc.GetString("virus-evolution-infectivity", ("percent", (int)(state.Infectivity * 100)));
            InfectedCountLabel.Text = Loc.GetString("virus-evolution-infected-count", ("count", state.InfectedCount));
            PointsPerSecondLabel.Text = Loc.GetString("virus-evolution-points-per-second", ("points", state.PointsPerSecond));

            VirusHealthLabel.Visible = true;
            InfectivityLabel.Visible = true;
            InfectedCountLabel.Visible = true;
            PointsPerSecondLabel.Visible = true;
        }

        _selectedActiveSymptom = null;
        _selectedActiveBody = null;

        DeleteSymptomButton.Disabled = true;
        DeleteBodyButton.Disabled = true;

        if (state.HasVirus == false)
        {
            VirusDataMissing.Visible = true;

            EvolutionServerMissing.Visible = false;
            EvolutionServerFar.Visible = false;
            EvolutionContents.Visible = false;

            WhitelistContents.Visible = false;

            BuyBodyButton.Visible = false;
            BuySymptomButton.Visible = false;
            AvailableSymptomsList.Visible = false;

            return;
        }
        else
        {
            VirusDataMissing.Visible = false;
        }

        if (!state.DataServerConnected || !state.SolutionAnalyzerConnected)
        {
            EvolutionServerMissing.Visible = true;
            EvolutionServerFar.Visible = false;
            EvolutionContents.Visible = false;

            WhitelistContents.Visible = false;

            BuyBodyButton.Visible = false;
            BuySymptomButton.Visible = false;
            AvailableSymptomsList.Visible = false;
        }
        else if (!state.DataServerInRange || !state.SolutionAnalyzerInRange)
        {
            EvolutionServerMissing.Visible = false;
            EvolutionServerFar.Visible = true;
            EvolutionContents.Visible = false;

            WhitelistContents.Visible = false;

            BuyBodyButton.Visible = false;
            BuySymptomButton.Visible = false;
            AvailableSymptomsList.Visible = false;
        }
        else
        {
            EvolutionServerMissing.Visible = false;
            EvolutionServerFar.Visible = false;
            EvolutionContents.Visible = true;

            WhitelistContents.Visible = true;

            BuyBodyButton.Visible = true;
            BuySymptomButton.Visible = true;
            AvailableSymptomsList.Visible = true;
        }
        if (state.NecroVirus is null)
        {
            HpLable.Visible = true;
            HpMulty.Visible = true;
            HpMulty_Value.Visible = true;
            DamageLable.Visible = true;
            DamageMulty.Visible = true;
            DamageMulty_Value.Visible = true;
            SpeedLable.Visible = true;
            SpeedMulty_Value.Visible = true;
            StaminaLable.Visible = true;
            StaminaMulty.Visible = true;
            StaminaMulty_Value.Visible = true;
            NecroSpecName.Visible = true;
            NecroSpecialEffectsList.Visible = true;
            FinalPriceLabel.Visible = true;
            ChangeNecroVirus.Visible = true;
        }
        var virusSystem = _entityManager.System<VirusSystem>();

        // Активные симптомы
        ActiveSymptomsList.Clear();
        if (state.ActiveSymptoms != null)
        {
            foreach (var active in state.ActiveSymptoms)
            {
                var price = virusSystem.GetSymptomDeletePrice(state.MultiPriceDeleteSymptom);
                if (_prototype.TryIndex(active, out var proto))
                {
                    ActiveSymptomsList.AddItem(
                        $"{proto.Name} ({price})",
                        metadata: active
                    );
                }
            }

            AvailableSymptomsList.Clear();
            _availableSymptoms.Clear();

            foreach (var proto in _prototype.EnumeratePrototypes<VirusSymptomPrototype>())
            {
                if (state.ActiveSymptoms.Contains(proto.ID))
                    continue;

                if (proto.DangerIndicator == DangerIndicatorSymptom.Cataclysm)
                    continue;

                var price = virusSystem.GetSymptomPrice(state.ActiveSymptoms, proto.ID);
                AvailableSymptomsList.AddItem(
                    $"{proto.Name} ({price})",
                    metadata: proto.ID
                );

                _availableSymptoms.Add(proto);
            }

        }
        if (state.BodyWhitelist != null)
        {
            ActiveBodiesList.Clear();
            foreach (var body in state.BodyWhitelist)
            {
                var price = virusSystem.GetBodyDeletePrice();
                if (_prototype.TryIndex(body, out var proto))
                {
                    ActiveBodiesList.AddItem(
                        $"{proto.Name} ({price})",
                        metadata: body
                    );
                }
            }

            AvailableBodiesList.Clear();
            _availableBodies.Clear();

            foreach (var proto in _prototype.EnumeratePrototypes<BodyPrototype>())
            {
                if (state.BodyWhitelist.Contains(proto.ID))
                    continue;

                if (BaseVirusSettings.BodyBlackList.Contains(proto.ID))
                    continue;

                var price = virusSystem.GetBodyPrice(state.BodyWhitelist);

                AvailableBodiesList.AddItem(
                    $"{proto.Name} ({price})",
                    metadata: proto.ID
                );

                _availableBodies.Add(proto);
            }

        }
    }

    private void OnAvailableSymptomSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (_lastUpdate == null)
            return;

        if (args.ItemIndex < 0)
        {
            BuySymptomButton.Disabled = true;
            SymptomCostLabel.Text = string.Empty;
            SymptomDescription.Clear();
            return;
        }

        if (args.ItemIndex >= _availableSymptoms.Count)
        {
            BuySymptomButton.Disabled = true;
            return;
        }

        var proto = _availableSymptoms[args.ItemIndex];

        SymptomDescription.SetMessage(proto.Description);

        var price = proto.Price
                    * Math.Max(1, _lastUpdate.ActiveSymptoms.Count);

        SymptomCostLabel.Text = Loc.GetString(
            "virus-evolution-cost-label",
            ("cost", price)
        );

        BuySymptomButton.Disabled = _lastUpdate.MutationPoints < price;
    }

    private void OnAvailableBodySelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (_lastUpdate == null)
            return;

        if (args.ItemIndex < 0 || args.ItemIndex >= _availableBodies.Count)
        {
            BuyBodyButton.Disabled = true;
            BodyCostLabel.Text = string.Empty;
            return;
        }

        var proto = _availableBodies[args.ItemIndex];

        var price = BaseVirusSettings.StaticBodyPrice
                    * Math.Max(1, _lastUpdate.BodyWhitelist.Count);

        BodyCostLabel.Text = Loc.GetString(
            "virus-evolution-cost-label",
            ("cost", price)
        );

        BuyBodyButton.Disabled = _lastUpdate.MutationPoints < price;
    }

    private void OnActiveSymptomSelected(ItemList.ItemListSelectedEventArgs args)
    {
        _selectedActiveSymptom = null;
        DeleteSymptomButton.Disabled = true;

        if (_lastUpdate == null || args.ItemIndex < 0)
            return;

        var item = ActiveSymptomsList[args.ItemIndex];
        if (item.Metadata is not ProtoId<VirusSymptomPrototype> id)
            return;

        _selectedActiveSymptom = id;

        var virusSystem = _entityManager.System<VirusSystem>();
        var deletePrice = virusSystem.GetSymptomDeletePrice(
            _lastUpdate.MultiPriceDeleteSymptom
        );

        DeleteSymptomButton.Disabled = _lastUpdate.MutationPoints < deletePrice;
    }

    private void OnActiveBodySelected(ItemList.ItemListSelectedEventArgs args)
    {
        _selectedActiveBody = null;
        DeleteBodyButton.Disabled = true;

        if (_lastUpdate == null || args.ItemIndex < 0)
            return;

        var item = ActiveBodiesList[args.ItemIndex];
        if (item.Metadata is not ProtoId<BodyPrototype> id)
            return;

        _selectedActiveBody = id;

        var virusSystem = _entityManager.System<VirusSystem>();
        var deletePrice = virusSystem.GetBodyDeletePrice();

        DeleteBodyButton.Disabled = _lastUpdate.MutationPoints < deletePrice;
    }

    public InfectionDeadStrainData GetInfectionDeadStrainData()
    {
        InfectionDeadStrainData infectionDeadStrainData = new InfectionDeadStrainData();
        infectionDeadStrainData.DamageMulty = DamageMulty.Value;
        infectionDeadStrainData.SpeedMulty = SpeedMulty.Value;
        infectionDeadStrainData.StaminaMulty = StaminaMulty.Value;
        infectionDeadStrainData.HpMulty = HpMulty.Value;
        return infectionDeadStrainData;
    }
}