// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System.Linq;
using Content.Shared.Body.Prototypes;
using Content.Shared.DeadSpace.Virus.Prototypes;
using Content.Shared.Virus;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.DeadSpace.Virus.UI;

[GenerateTypedNameReferences]
public sealed partial class VirusEvolutionConsoleWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    private VirusEvolutionConsoleBoundUserInterfaceState? _lastUpdate;
    private readonly List<VirusSymptomPrototype> _availableSymptoms = new();

    public VirusEvolutionConsoleWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        AvailableSymptomsList.OnItemSelected += OnAvailableSymptomSelected;
    }

    public void Populate(VirusEvolutionConsoleBoundUserInterfaceState state)
    {
        _lastUpdate = state;
        MutationPointsLabel.Text = Loc.GetString("virus-evolution-mutation-points", ("points", state.MutationPoints));

        if (state.HasVirus == false)
        {
            VirusDataMissing.Visible = true;

            EvolutionServerMissing.Visible = false;
            EvolutionServerFar.Visible = false;
            EvolutionContents.Visible = false;

            WhitelistServerMissing.Visible = false;
            WhitelistServerFar.Visible = false;
            WhitelistContents.Visible = false;

            BuyBodyButton.Visible = false;
            BuySymptomButton.Visible = false;
            AvailableSymptomsList.Visible = false;
            BodyWhitelistList.Visible = false;
            return;
        }
        else
        {
            VirusDataMissing.Visible = false;
        }

        if (!state.DataServerConnected || !state.SolutionAnalyzerConnected)
        {
            EvolutionServerMissing.Visible = true;
            EvolutionServerFar.Visible = false;
            EvolutionContents.Visible = false;

            WhitelistServerMissing.Visible = true;
            WhitelistServerFar.Visible = false;
            WhitelistContents.Visible = false;

            BuyBodyButton.Visible = false;
            BuySymptomButton.Visible = false;
            AvailableSymptomsList.Visible = false;
            BodyWhitelistList.Visible = false;
        }
        else if (!state.DataServerInRange || !state.SolutionAnalyzerInRange)
        {
            EvolutionServerMissing.Visible = false;
            EvolutionServerFar.Visible = true;
            EvolutionContents.Visible = false;

            WhitelistServerMissing.Visible = false;
            WhitelistServerFar.Visible = true;
            WhitelistContents.Visible = false;

            BuyBodyButton.Visible = false;
            BuySymptomButton.Visible = false;
            AvailableSymptomsList.Visible = false;
            BodyWhitelistList.Visible = false;
        }
        else
        {
            EvolutionServerMissing.Visible = false;
            EvolutionServerFar.Visible = false;
            EvolutionContents.Visible = true;

            WhitelistServerMissing.Visible = false;
            WhitelistServerFar.Visible = false;
            WhitelistContents.Visible = true;

            BuyBodyButton.Visible = true;
            BuySymptomButton.Visible = true;
            AvailableSymptomsList.Visible = true;
            BodyWhitelistList.Visible = true;
        }

        // Активные симптомы
        ActiveSymptomsList.Clear();
        if (state.ActiveSymptoms != null)
        {
            foreach (var active in state.ActiveSymptoms)
            {
                if (_prototype.TryIndex(active, out var proto))
                    ActiveSymptomsList.AddItem(proto.Name.ToString());
            }

            AvailableSymptomsList.Clear();
            _availableSymptoms.Clear();

            foreach (var proto in _prototype.EnumeratePrototypes<VirusSymptomPrototype>())
            {
                if (state.ActiveSymptoms.Contains(proto.ID))
                    continue;

                var price = proto.Price * Math.Max(1, state.ActiveSymptoms.Count);
                AvailableSymptomsList.AddItem($"{proto.Name} ({price})");

                _availableSymptoms.Add(proto);
            }

        }
        if (state.BodyWhitelist != null)
        {
            BodyWhitelistList.Clear();
            foreach (var body in state.BodyWhitelist)
            {
                BodyWhitelistList.AddItem(body.ToString());
            }

            foreach (var proto in _prototype.EnumeratePrototypes<BodyPrototype>())
            {
                if (!state.BodyWhitelist.Contains(proto.ID))
                {
                    var price = BaseVirusSettings.StaticBodyPrice * Math.Max(1, state.BodyWhitelist.Count);
                    BodyWhitelistList.AddItem($"{proto.Name}-({price})");
                }
            }
        }

        var selectedBody = BodyWhitelistList.GetSelected();
        var selectedSymp = AvailableSymptomsList.GetSelected();

        BuyBodyButton.Disabled = !selectedBody.Any();
        BuySymptomButton.Disabled = !selectedSymp.Any();
    }

    private void OnAvailableSymptomSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (_lastUpdate == null)
            return;

        if (args.ItemIndex < 0 || args.ItemIndex >= _availableSymptoms.Count)
            return;

        var proto = _availableSymptoms[args.ItemIndex];

        SymptomDescription.SetMessage(proto.Description);

        var price = proto.Price * Math.Max(1, _lastUpdate.ActiveSymptoms.Count);
        SymptomCostLabel.Text = Loc.GetString(
            "virus-evolution-cost-label",
            ("cost", price)
        );

        BuySymptomButton.Disabled = _lastUpdate.MutationPoints < price;
    }

}
