using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.Virus;
using System.Linq;

namespace Content.Client.DeadSpace.Virus.UI;

[GenerateTypedNameReferences]
public sealed partial class VirusDiagnoserConsoleWindow : DefaultWindow
{
    private VirusDiagnoserConsoleBoundUserInterfaceState? _lastUpdate;

    public VirusDiagnoserConsoleWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        // Подписываемся на выбор штамма, чтобы кнопки обновлялись
        StrainList.OnItemSelected += _ =>
        {
            UpdateServerTabButtons();
        };
    }

    public void Populate(VirusDiagnoserConsoleBoundUserInterfaceState state)
    {
        _lastUpdate = state;

        // Состояние 1: сервер недоступен
        if (!state.DataServerConnected)
        {
            ServerMissing.Visible = true;
            ServerFar.Visible = false;
            ServerContents.Visible = false;
        }
        // Состояние 2: сервер далеко
        else if (!state.DataServerInRange)
        {
            ServerMissing.Visible = false;
            ServerFar.Visible = true;
            ServerContents.Visible = false;
        }
        // Состояние 3: сервер доступен
        else
        {
            ServerMissing.Visible = false;
            ServerFar.Visible = false;
            ServerContents.Visible = true;

            // Обновление списка штаммов
            StrainList.Clear();

            foreach (var strain in state.Strains)
            {
                StrainList.AddItem(strain);
            }

            UpdateServerTabButtons();
        }

        if (!state.DiagnoserConnected)
        {
            DiagnoserMissing.Visible = true;
            DiagnoserFar.Visible = false;
            DiagnoserContents.Visible = false;
        }
        else if (!state.DiagnoserInRange)
        {
            DiagnoserMissing.Visible = false;
            DiagnoserFar.Visible = true;
            DiagnoserContents.Visible = false;
        }
        else
        {
            DiagnoserMissing.Visible = false;
            DiagnoserFar.Visible = false;
            DiagnoserContents.Visible = true;
        }
    }

    private void UpdateServerTabButtons()
    {
        var selectedItems = StrainList.GetSelected();

        // Кнопки недоступны, если ничего не выбрано
        bool nothingSelected = !selectedItems.Any();
        DeleteStrainButton.Disabled = nothingSelected;
        PrintReportButton.Disabled = nothingSelected;
        GenerateVirusButton.Disabled = nothingSelected;
    }

}
