// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System.Linq;
using Content.Shared.Body.Prototypes;
using Content.Shared.DeadSpace.Virus.Prototypes;
using Content.Shared.Virus;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.DeadSpace.Virus.UI;

[GenerateTypedNameReferences]
public sealed partial class VirusEvolutionConsoleWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    private VirusEvolutionConsoleBoundUserInterfaceState? _lastUpdate;
    private readonly List<VirusSymptomPrototype> _availableSymptoms = new();
    private readonly List<BodyPrototype> _availableBodies = new();


    public VirusEvolutionConsoleWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        AvailableSymptomsList.OnItemSelected += OnAvailableSymptomSelected;
        AvailableBodiesList.OnItemSelected += OnAvailableBodySelected;
    }

    public void Populate(VirusEvolutionConsoleBoundUserInterfaceState state)
    {
        _lastUpdate = state;
        MutationPointsLabel.Text = Loc.GetString("virus-evolution-mutation-points", ("points", state.MutationPoints));
        WhitelistMutationPointsLabel.Text = Loc.GetString("virus-evolution-mutation-points", ("points", state.MutationPoints));

        if (state.HasVirus == false)
        {
            VirusDataMissing.Visible = true;

            EvolutionServerMissing.Visible = false;
            EvolutionServerFar.Visible = false;
            EvolutionContents.Visible = false;

            WhitelistContents.Visible = false;

            BuyBodyButton.Visible = false;
            BuySymptomButton.Visible = false;
            AvailableSymptomsList.Visible = false;

            return;
        }
        else
        {
            VirusDataMissing.Visible = false;
        }

        if (!state.DataServerConnected || !state.SolutionAnalyzerConnected)
        {
            EvolutionServerMissing.Visible = true;
            EvolutionServerFar.Visible = false;
            EvolutionContents.Visible = false;

            WhitelistContents.Visible = false;

            BuyBodyButton.Visible = false;
            BuySymptomButton.Visible = false;
            AvailableSymptomsList.Visible = false;
        }
        else if (!state.DataServerInRange || !state.SolutionAnalyzerInRange)
        {
            EvolutionServerMissing.Visible = false;
            EvolutionServerFar.Visible = true;
            EvolutionContents.Visible = false;

            WhitelistContents.Visible = false;

            BuyBodyButton.Visible = false;
            BuySymptomButton.Visible = false;
            AvailableSymptomsList.Visible = false;
        }
        else
        {
            EvolutionServerMissing.Visible = false;
            EvolutionServerFar.Visible = false;
            EvolutionContents.Visible = true;

            WhitelistContents.Visible = true;

            BuyBodyButton.Visible = true;
            BuySymptomButton.Visible = true;
            AvailableSymptomsList.Visible = true;
        }

        // Активные симптомы
        ActiveSymptomsList.Clear();
        if (state.ActiveSymptoms != null)
        {
            foreach (var active in state.ActiveSymptoms)
            {
                if (_prototype.TryIndex(active, out var proto))
                    ActiveSymptomsList.AddItem(proto.Name.ToString());
            }

            AvailableSymptomsList.Clear();
            _availableSymptoms.Clear();

            foreach (var proto in _prototype.EnumeratePrototypes<VirusSymptomPrototype>())
            {
                if (state.ActiveSymptoms.Contains(proto.ID))
                    continue;

                var price = proto.Price * Math.Max(1, state.ActiveSymptoms.Count);
                AvailableSymptomsList.AddItem(
                    $"{proto.Name} ({price})",
                    metadata: proto.ID
                );

                _availableSymptoms.Add(proto);
            }

        }
        if (state.BodyWhitelist != null)
        {
            ActiveBodiesList.Clear();

            foreach (var body in state.BodyWhitelist)
            {
                if (_prototype.TryIndex(body, out var proto))
                    ActiveBodiesList.AddItem(proto.Name);
            }


            AvailableBodiesList.Clear();
            _availableBodies.Clear();

            foreach (var proto in _prototype.EnumeratePrototypes<BodyPrototype>())
            {
                if (state.BodyWhitelist.Contains(proto.ID))
                    continue;

                var price = BaseVirusSettings.StaticBodyPrice
                            * Math.Max(1, state.BodyWhitelist.Count);

                AvailableBodiesList.AddItem(
                    $"{proto.Name} ({price})",
                    metadata: proto.ID
                );

                _availableBodies.Add(proto);
            }

        }
    }

    private void OnAvailableSymptomSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (_lastUpdate == null)
            return;

        if (args.ItemIndex < 0)
        {
            BuySymptomButton.Disabled = true;
            SymptomCostLabel.Text = string.Empty;
            SymptomDescription.Clear();
            return;
        }

        if (args.ItemIndex >= _availableSymptoms.Count)
        {
            BuySymptomButton.Disabled = true;
            return;
        }

        var proto = _availableSymptoms[args.ItemIndex];

        SymptomDescription.SetMessage(proto.Description);

        var price = proto.Price
                    * Math.Max(1, _lastUpdate.ActiveSymptoms.Count);

        SymptomCostLabel.Text = Loc.GetString(
            "virus-evolution-cost-label",
            ("cost", price)
        );

        BuySymptomButton.Disabled = _lastUpdate.MutationPoints < price;
    }

    private void OnAvailableBodySelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (_lastUpdate == null)
            return;

        if (args.ItemIndex < 0 || args.ItemIndex >= _availableBodies.Count)
        {
            BuyBodyButton.Disabled = true;
            BodyCostLabel.Text = string.Empty;
            return;
        }

        var proto = _availableBodies[args.ItemIndex];

        var price = BaseVirusSettings.StaticBodyPrice
                    * Math.Max(1, _lastUpdate.BodyWhitelist.Count);

        BodyCostLabel.Text = Loc.GetString(
            "virus-evolution-cost-label",
            ("cost", price)
        );

        BuyBodyButton.Disabled = _lastUpdate.MutationPoints < price;
    }



}
