using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.DeadSpace.Ninja.Components;

namespace Content.Client.DeadSpace.Ninja.UI;

[GenerateTypedNameReferences]
public sealed partial class NinjaScannerWindow : FancyWindow
{
    public event Action<NetEntity>? OnApplyDisguise;

    public NinjaScannerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(List<NinjaScanData> targets)
    {
        TargetsContainer.RemoveAllChildren();

        if (targets.Count == 0)
        {
            TargetsContainer.AddChild(new Label
            {
                Text = Loc.GetString("ninja-scanner-window-empty"),
                Align = Label.AlignMode.Center
            });
            return;
        }

        foreach (var data in targets)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(0, 0, 0, 6)
            };

            var label = new Label
            {
                Text = data.Name,
                HorizontalExpand = true
            };
            
            var button = new Button
            {
                Text = Loc.GetString("ninja-scanner-window-disguise-button")
            };

            var target = data.Target;
            button.OnPressed += _ => OnApplyDisguise?.Invoke(target);

            row.AddChild(label);
            row.AddChild(button);
            TargetsContainer.AddChild(row);
        }
    }
}