// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT


using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.ResourceManagement;
using Robust.Client.Graphics;
using Content.Client.Resources;

namespace Content.Client.DeadSpace.Ninja.UI;

[GenerateTypedNameReferences]
public sealed partial class SpiderOSWindow : FancyWindow
{
    [Dependency] private readonly IResourceCache _cache = default!;

    public SpiderOSWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var panelTex = _cache.GetTexture("/Textures/Interface/Nano/button.svg.96dpi.png");

        if (BackPanel.PanelOverride is StyleBoxTexture tex)
            tex.Texture = panelTex;
    }
}
