using System.Numerics;
using Content.Shared.DeadSpace.BSAConsole;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client.DeadSpace.BSAConsole;

[GenerateTypedNameReferences]
public sealed partial class BSAConsoleWindow : DefaultWindow
{
    public event Action<float, float>? OnFirePressed;
    public event Action<string>? OnSwitchViewPressed;
    public event Action<string>? OnSelectGridPressed;
    public event Action? OnEjectDiskPressed;

    private bool _viewDropdownOpen;
    private IEntityManager _entMan = default!;
    private BSAConsoleUiState? _lastState;

    public BSAConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _entMan = IoCManager.Resolve<IEntityManager>();

        ViewModeButton.OnPressed += _ => ToggleViewDropdown();
        FireButton.OnPressed += _ => OnFirePressed?.Invoke(GetX(), GetY());
        EjectDiskButton.OnPressed += _ => OnEjectDiskPressed?.Invoke();

        RadarScreen.OnRadarClick += OnRadarClicked;
        MapScreen.OnMapClick += OnMapClicked;
    }

    public void UpdateState(BSAConsoleUiState state)
    {
        _lastState = state;
        UpdateConnection(state);
        UpdateCooldown(state);
        UpdateViewLabel(state);
        UpdateRadar(state);
        UpdateMapView(state);
        UpdateDisk(state);
        RebuildDropdown(state);
    }

    private void UpdateConnection(BSAConsoleUiState state)
    {
        if (state.IsConnected)
        {
            BSAConnectionLabel.Text = state.BSAName ?? "БСА (Подключено)";
            BSAConnectionLabel.FontColorOverride = Color.FromHex("#00FF00");
            ErrorLabel.Visible = false;
            FireButton.Disabled = state.IsOnCooldown;
        }
        else
        {
            BSAConnectionLabel.Text = "Не подключено";
            BSAConnectionLabel.FontColorOverride = Color.FromHex("#FF4444");
            ErrorLabel.Text = "ОШИБКА: Связь отсутствует.\nИспользуйте Сетевой конфигуратор";
            ErrorLabel.Visible = true;
            FireButton.Disabled = true;
        }
    }

    private void UpdateCooldown(BSAConsoleUiState state)
    {
        if (state.IsOnCooldown)
        {
            var remaining = (int)Math.Ceiling(state.CooldownRemaining);
            CooldownLabel.Text = $"ОХЛАЖДЕНИЕ: ОСТАЛОСЬ {remaining} сек.";
            CooldownLabel.FontColorOverride = Color.FromHex("#FF8800");
            CooldownBar.Value = state.CooldownDuration - state.CooldownRemaining;
            CooldownBar.MaxValue = state.CooldownDuration;

            var panelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#442200"),
                BorderColor = Color.FromHex("#FF8800"),
                BorderThickness = new Thickness(1),
            };
            CooldownPanel.PanelOverride = panelOverride;
            FireButton.Disabled = true;
        }
        else
        {
            CooldownLabel.Text = "ГОТОВА К ЗАЛПУ";
            CooldownLabel.FontColorOverride = Color.FromHex("#00FF00");
            CooldownBar.Value = 0;

            var panelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#003300"),
                BorderColor = Color.FromHex("#00FF00"),
                BorderThickness = new Thickness(1),
            };
            CooldownPanel.PanelOverride = panelOverride;
        }
    }

    private void UpdateViewLabel(BSAConsoleUiState state)
    {
        var modeText = state.CurrentViewMode switch
        {
            "MassScanner" => "СКАНЕР МАСС",
            "Grid" => state.SelectedGridName != null ? $"ГРИД: {state.SelectedGridName}" : "СКАНЕР МАСС",
            _ => state.CurrentViewMode,
        };

        ViewModeButton.Text = $"РЕЖИМ: {modeText}";

        var isMapMode = state.CurrentViewMode == "Grid";
        var isRadarMode = state.CurrentViewMode == "MassScanner";

        RadarScreen.Visible = isRadarMode;
        MapScreen.Visible = isMapMode;

        if (isMapMode && state.SelectedGridName != null)
        {
            SelectedGridLabel.Text = $"Целевой грид: {state.SelectedGridName}";
            SelectedGridLabel.Visible = true;
        }
        else
        {
            SelectedGridLabel.Visible = false;
        }
    }

    private void UpdateRadar(BSAConsoleUiState state)
    {
        if (state.CurrentViewMode != "MassScanner")
            return;

        NavInterfaceState? radarState = state.HasDisk ? state.DiskRadarState : state.LocalRadarState;
        radarState ??= state.LocalRadarState;

        if (radarState != null)
            RadarScreen.UpdateState(radarState);
    }

    private void UpdateMapView(BSAConsoleUiState state)
    {
        if (state.CurrentViewMode != "Grid" || state.SelectedGridUid == null)
            return;

        var targetUid = _entMan.GetEntity(state.SelectedGridUid.Value);
        if (MapScreen.MapUid != targetUid)
        {
            MapScreen.MapUid = targetUid;
            MapScreen.ForceNavMapUpdate();
        }
    }

    private void UpdateDisk(BSAConsoleUiState state)
    {
        if (state.HasDisk)
        {
            DiskStatusLabel.Text = $"Сектор: {state.TargetMapName ?? "Неизвестный"}";
            DiskStatusLabel.FontColorOverride = Color.FromHex("#00FF00");
            EjectDiskButton.Visible = true;
        }
        else
        {
            DiskStatusLabel.Text = "Вставьте координатный диск";
            DiskStatusLabel.FontColorOverride = Color.FromHex("#FFaa00");
            EjectDiskButton.Visible = false;
        }
    }

    private void RebuildDropdown(BSAConsoleUiState state)
    {
        DropdownContainer.RemoveAllChildren();

        // "Сканер масс" always first
        var scannerBtn = new Button
        {
            Text = "Сканер масс",
            TextAlign = Label.AlignMode.Left,
            MinHeight = 28,
        };
        scannerBtn.OnPressed += _ =>
        {
            _viewDropdownOpen = false;
            ViewDropdownPanel.Visible = false;
            OnSwitchViewPressed?.Invoke("MassScanner");
        };
        DropdownContainer.AddChild(scannerBtn);

        // Separator
        if (state.AllGrids.Count > 0)
        {
            var sep = new PanelContainer { MinHeight = 1 };
            sep.PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#333355") };
            DropdownContainer.AddChild(sep);
        }

        // One button per grid
        foreach (var grid in state.AllGrids)
        {
            var isSelected = grid.Name == state.SelectedGridName && state.CurrentViewMode == "Grid";
            var label = grid.Source == "disk" ? $"{grid.Name} [Д]" : grid.Name;

            var btn = new Button
            {
                Text = label,
                TextAlign = Label.AlignMode.Left,
                MinHeight = 28,
                Disabled = isSelected,
            };
            var capturedGrid = grid.Name;
            btn.OnPressed += _ =>
            {
                _viewDropdownOpen = false;
                ViewDropdownPanel.Visible = false;
                OnSelectGridPressed?.Invoke(capturedGrid);
            };
            DropdownContainer.AddChild(btn);
        }

        // If no grids at all
        if (state.AllGrids.Count == 0)
        {
            var noGrids = new Label
            {
                Text = "  Гриды не найдены",
                FontColorOverride = Color.FromHex("#FFaa00"),
            };
            DropdownContainer.AddChild(noGrids);
        }
    }

    private void ToggleViewDropdown()
    {
        _viewDropdownOpen = !_viewDropdownOpen;
        ViewDropdownPanel.Visible = _viewDropdownOpen;
    }

    private static readonly System.Globalization.CultureInfo Inv = System.Globalization.CultureInfo.InvariantCulture;

    private void OnRadarClicked(EntityCoordinates coords)
    {
        CoordinateX.Text = coords.X.ToString("F1", Inv);
        CoordinateY.Text = coords.Y.ToString("F1", Inv);
    }

    private void OnMapClicked(MapCoordinates mapPos)
    {
        CoordinateX.Text = mapPos.X.ToString("F1", Inv);
        CoordinateY.Text = mapPos.Y.ToString("F1", Inv);
    }

    private float GetX()
    {
        if (float.TryParse(CoordinateX.Text, System.Globalization.NumberStyles.Float, Inv, out var x))
            return x;
        return 0f;
    }

    private float GetY()
    {
        if (float.TryParse(CoordinateY.Text, System.Globalization.NumberStyles.Float, Inv, out var y))
            return y;
        return 0f;
    }
}
