using System.Numerics;
using Content.Shared.DeadSpace.BSAConsole;
using Content.Shared.Pinpointer;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;

namespace Content.Client.DeadSpace.BSAConsole;

[GenerateTypedNameReferences]
public sealed partial class BSAConsoleWindow : DefaultWindow
{
    public event Action<float, float>? OnFirePressed;
    public event Action<string>? OnSwitchViewPressed;
    public event Action<string>? OnSelectGridPressed;
    public event Action? OnEjectDiskPressed;

    private IEntityManager _entMan = default!;
    private BSAConsoleUiState? _lastState;
    private Popup _dropdownPopup = default!;
    private BoxContainer _dropdownContainer = default!;

    private static readonly Color BgDark = Color.FromHex("#191920FF");
    private static readonly Color BgPanel = Color.FromHex("#1A1A24");
    private static readonly Color Border = Color.FromHex("#2a2a35");
    private static readonly Color Green = Color.FromHex("#54D98C");
    private static readonly Color GreenDark = Color.FromHex("#2A4A2A");
    private static readonly Color GreenBg = Color.FromHex("#1A2A1A");
    private static readonly Color Red = Color.FromHex("#D95454");
    private static readonly Color Gold = Color.FromHex("#D9A83C");
    private static readonly Color Muted = Color.FromHex("#3C3C50");
    private static readonly Color Orange = Color.FromHex("#D98C3C");
    private static readonly Color OrangeBg = Color.FromHex("#2A1A0A");
    private static readonly Color OrangeBorder = Color.FromHex("#4A2A0A");

    public BSAConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _entMan = IoCManager.Resolve<IEntityManager>();

        ViewModeButton.OnPressed += _ => ToggleDropdown();
        FireButton.OnPressed += _ => OnFirePressed?.Invoke(GetX(), GetY());
        EjectDiskButton.OnPressed += _ => OnEjectDiskPressed?.Invoke();

        RadarScreen.OnRadarClick += OnRadarClicked;
        MapScreen.OnMapClick += OnMapClicked;

        BuildDropdownPopup();
    }

    public void UpdateState(BSAConsoleUiState state)
    {
        _lastState = state;
        UpdateConnection(state);
        UpdateCooldown(state);
        UpdateViewLabel(state);
        UpdateRadar(state);
        UpdateMapView(state);
        UpdateDisk(state);
    }

    private void UpdateConnection(BSAConsoleUiState state)
    {
        if (state.IsConnected)
        {
            BSAConnectionLabel.Text = state.BSAName ?? "BSA";
            BSAConnectionLabel.FontColorOverride = Green;
            ErrorLabel.Visible = false;
            FireButton.Disabled = state.IsOnCooldown;
        }
        else
        {
            BSAConnectionLabel.Text = "OFFLINE";
            BSAConnectionLabel.FontColorOverride = Red;
            ErrorLabel.Text = "NET SVYAZI";
            ErrorLabel.Visible = true;
            FireButton.Disabled = true;
        }
    }

    private void UpdateCooldown(BSAConsoleUiState state)
    {
        if (state.IsOnCooldown)
        {
            var remaining = (int)Math.Ceiling(state.CooldownRemaining);
            CooldownLabel.Text = $"COOLING: {remaining}s";
            CooldownLabel.FontColorOverride = Orange;
            CooldownBar.Value = state.CooldownDuration - state.CooldownRemaining;
            CooldownBar.MaxValue = state.CooldownDuration;

            StatusPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = OrangeBg,
                BorderColor = OrangeBorder,
                BorderThickness = new Thickness(1),
            };
            FireButton.Disabled = true;
        }
        else
        {
            CooldownLabel.Text = "READY";
            CooldownLabel.FontColorOverride = Green;
            CooldownBar.Value = 0;

            StatusPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = GreenBg,
                BorderColor = GreenDark,
                BorderThickness = new Thickness(1),
            };
        }
    }

    private void UpdateViewLabel(BSAConsoleUiState state)
    {
        var modeText = state.CurrentViewMode switch
        {
            "MassScannerLocal" => "SKANER",
            "MassScannerDisk" => "SKANER *",
            "Grid" => state.SelectedGridName != null ? state.SelectedGridName : "SKANER",
            _ => state.CurrentViewMode,
        };

        ViewModeButton.Text = $"REZHIM: {modeText}";

        var isMapMode = state.CurrentViewMode == "Grid";

        if (isMapMode && state.SelectedGridUid != null)
        {
            var targetUid = _entMan.GetEntity(state.SelectedGridUid.Value);
            var hasNavMap = _entMan.TryGetComponent<NavMapComponent>(targetUid, out _);

            RadarScreen.Visible = !hasNavMap;
            MapScreen.Visible = hasNavMap;

            if (hasNavMap && MapScreen.MapUid != targetUid)
            {
                MapScreen.MapUid = targetUid;
                MapScreen.ForceNavMapUpdate();
            }

            SelectedGridLabel.Text = state.SelectedGridName;
            SelectedGridLabel.Visible = true;
        }
        else
        {
            RadarScreen.Visible = true;
            MapScreen.Visible = false;
            SelectedGridLabel.Visible = false;
        }
    }

    private void UpdateRadar(BSAConsoleUiState state)
    {
        if (state.CurrentViewMode == "MassScannerDisk" && state.DiskRadarState != null)
        {
            if (RadarScreen.Visible)
                RadarScreen.UpdateState(state.DiskRadarState);
        }
        else
        {
            if (state.LocalRadarState != null && RadarScreen.Visible)
                RadarScreen.UpdateState(state.LocalRadarState);
        }
    }

    private void UpdateMapView(BSAConsoleUiState state)
    {
    }

    private void UpdateDisk(BSAConsoleUiState state)
    {
        if (state.HasDisk)
        {
            DiskStatusLabel.Text = state.TargetMapName ?? "---";
            DiskStatusLabel.FontColorOverride = Green;
            EjectDiskButton.Visible = true;
        }
        else
        {
            DiskStatusLabel.Text = "DISK NE VSTAVLEN";
            DiskStatusLabel.FontColorOverride = Gold;
            EjectDiskButton.Visible = false;
        }
    }

    #region Dropdown Popup

    private void BuildDropdownPopup()
    {
        _dropdownContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 1,
        };

        var panel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = BgPanel,
                BorderColor = Border,
                BorderThickness = new Thickness(1),
            },
            Children =
            {
                new ScrollContainer
                {
                    MaxHeight = 200,
                    HScrollEnabled = false,
                    Children = { _dropdownContainer },
                }
            },
        };

        _dropdownPopup = new Popup { Children = { panel } };
        _dropdownPopup.OnPopupHide += OnPopupClosed;
    }

    private void ToggleDropdown()
    {
        if (_dropdownPopup.Visible)
        {
            _dropdownPopup.Close();
        }
        else
        {
            OpenDropdown();
        }
    }

    private void OpenDropdown()
    {
        if (_lastState == null)
            return;

        _dropdownContainer.RemoveAllChildren();

        var localActive = _lastState.CurrentViewMode == "MassScannerLocal" || _lastState.CurrentViewMode == "MassScanner";
        AddDropdownButton("SKANER MASS", "MassScannerLocal", localActive);

        if (_lastState.HasDisk)
        {
            var diskActive = _lastState.CurrentViewMode == "MassScannerDisk";
            AddDropdownButton($"SKANER MASS *", "MassScannerDisk", diskActive);
        }

        if (_lastState.AllGrids.Count > 0)
        {
            AddSeparator();
        }

        foreach (var grid in _lastState.AllGrids)
        {
            var isSelected = grid.Name == _lastState.SelectedGridName && _lastState.CurrentViewMode == "Grid";
            var label = grid.Source == "disk" ? $"{grid.Name} *" : grid.Name;

            var btn = new Button
            {
                Text = label,
                TextAlign = Label.AlignMode.Left,
                MinHeight = 26,
                Disabled = isSelected,
            };
            var capturedGrid = grid.Name;
            btn.OnPressed += _ =>
            {
                _dropdownPopup.Close();
                OnSelectGridPressed?.Invoke(capturedGrid);
            };
            _dropdownContainer.AddChild(btn);
        }

        if (_lastState.AllGrids.Count == 0)
        {
            var noGrids = new Label
            {
                Text = "  NO GRIDS",
                FontColorOverride = Muted,
            };
            _dropdownContainer.AddChild(noGrids);
        }

        var globalPos = ViewModeButton.GlobalPosition;
        globalPos.Y += ViewModeButton.Size.Y + 1;
        _dropdownContainer.Measure(Window?.Size ?? Vector2Helpers.Infinity);
        var (minX, minY) = _dropdownContainer.DesiredSize;
        var box = UIBox2.FromDimensions(globalPos, new Vector2(Math.Max(minX, ViewModeButton.Width), minY));

        UserInterfaceManager.ModalRoot.AddChild(_dropdownPopup);
        _dropdownPopup.Open(box);
    }

    private void AddDropdownButton(string text, string? viewMode, bool disabled)
    {
        var btn = new Button
        {
            Text = text,
            TextAlign = Label.AlignMode.Left,
            MinHeight = 26,
            Disabled = disabled,
        };

        var capturedMode = viewMode;
        btn.OnPressed += _ =>
        {
            _dropdownPopup.Close();
            OnSwitchViewPressed?.Invoke(capturedMode ?? "MassScannerLocal");
        };

        _dropdownContainer.AddChild(btn);
    }

    private void AddSeparator()
    {
        var sep = new PanelContainer { MinHeight = 1 };
        sep.PanelOverride = new StyleBoxFlat { BackgroundColor = Border };
        _dropdownContainer.AddChild(sep);
    }

    private void OnPopupClosed()
    {
        UserInterfaceManager.ModalRoot.RemoveChild(_dropdownPopup);
    }

    #endregion

    private static readonly System.Globalization.CultureInfo Inv = System.Globalization.CultureInfo.InvariantCulture;

    private void OnRadarClicked(EntityCoordinates coords)
    {
        CoordinateX.Text = coords.X.ToString("F1", Inv);
        CoordinateY.Text = coords.Y.ToString("F1", Inv);
    }

    private void OnMapClicked(MapCoordinates mapPos)
    {
        CoordinateX.Text = mapPos.X.ToString("F1", Inv);
        CoordinateY.Text = mapPos.Y.ToString("F1", Inv);
    }

    private float GetX()
    {
        if (float.TryParse(CoordinateX.Text, System.Globalization.NumberStyles.Float, Inv, out var x))
            return x;
        return 0f;
    }

    private float GetY()
    {
        if (float.TryParse(CoordinateY.Text, System.Globalization.NumberStyles.Float, Inv, out var y))
            return y;
        return 0f;
    }
}
