using System.Numerics;
using Content.Shared.DeadSpace.BSAConsole;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client.DeadSpace.BSAConsole;

[GenerateTypedNameReferences]
public sealed partial class BSAConsoleWindow : DefaultWindow
{
    public event Action<float, float>? OnFirePressed;
    public event Action<string>? OnSwitchViewPressed;
    public event Action<string>? OnSelectGridPressed;
    public event Action? OnEjectDiskPressed;

    private bool _viewDropdownOpen;
    private bool _isMapMode;
    private IEntityManager _entMan = default!;

    public BSAConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _entMan = IoCManager.Resolve<IEntityManager>();

        ViewModeButton.OnPressed += _ => ToggleViewDropdown();
        ModeMassScanner.OnPressed += _ => SelectViewMode("MassScanner");
        ModeStationGrid.OnPressed += _ => SelectViewMode("Grid: Станция");
        FireButton.OnPressed += _ => OnFirePressed?.Invoke(GetX(), GetY());
        EjectDiskButton.OnPressed += _ => OnEjectDiskPressed?.Invoke();

        // Radar click → fill coordinates
        RadarScreen.OnRadarClick += OnRadarClicked;
        // Map click → fill coordinates
        MapScreen.OnMapClick += OnMapClicked;
    }

    public void UpdateState(BSAConsoleUiState state)
    {
        UpdateConnection(state);
        UpdateCooldown(state);
        UpdateViewMode(state);
        UpdateRadar(state);
        UpdateMapView(state);
        UpdateDisk(state);
        UpdateLogs(state);
    }

    private void UpdateConnection(BSAConsoleUiState state)
    {
        if (state.IsConnected)
        {
            BSAConnectionLabel.Text = state.BSAName ?? "БСА (Подключено)";
            BSAConnectionLabel.FontColorOverride = Color.FromHex("#00FF00");
            ErrorLabel.Visible = false;
            FireButton.Disabled = state.IsOnCooldown;
        }
        else
        {
            BSAConnectionLabel.Text = "Не подключено";
            BSAConnectionLabel.FontColorOverride = Color.FromHex("#FF4444");
            ErrorLabel.Text = "ОШИБКА: Связь отсутствует.\nИспользуйте Сетевой конфигуратор";
            ErrorLabel.Visible = true;
            FireButton.Disabled = true;
        }
    }

    private void UpdateCooldown(BSAConsoleUiState state)
    {
        if (state.IsOnCooldown)
        {
            var remaining = (int)Math.Ceiling(state.CooldownRemaining);
            CooldownLabel.Text = $"ОХЛАЖДЕНИЕ: ОСТАЛОСЬ {remaining} сек.";
            CooldownLabel.FontColorOverride = Color.FromHex("#FF8800");
            CooldownBar.Value = state.CooldownDuration - state.CooldownRemaining;
            CooldownBar.MaxValue = state.CooldownDuration;

            var panelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#442200"),
                BorderColor = Color.FromHex("#FF8800"),
                BorderThickness = new Thickness(1),
            };
            CooldownPanel.PanelOverride = panelOverride;
            FireButton.Disabled = true;
        }
        else
        {
            CooldownLabel.Text = "ГОТОВА К ЗАЛПУ";
            CooldownLabel.FontColorOverride = Color.FromHex("#00FF00");
            CooldownBar.Value = 0;

            var panelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#003300"),
                BorderColor = Color.FromHex("#00FF00"),
                BorderThickness = new Thickness(1),
            };
            CooldownPanel.PanelOverride = panelOverride;
        }
    }

    private void UpdateViewMode(BSAConsoleUiState state)
    {
        var modeText = state.CurrentViewMode switch
        {
            "MassScanner" => "СКАНЕР МАСС",
            "Grid" => $"ГРИД: {state.SelectedGridName ?? "???"}",
            _ when state.CurrentViewMode.StartsWith("Grid: ") => $"ГРИД: {state.CurrentViewMode["Grid: ".Length..]}",
            _ => state.CurrentViewMode,
        };

        ViewModeButton.Text = $"РЕЖИМ: {modeText}";

        _isMapMode = state.CurrentViewMode != "MassScanner";

        RadarScreen.Visible = !_isMapMode;
        MapScreen.Visible = _isMapMode;

        if (_isMapMode && state.SelectedGridName != null)
        {
            SelectedGridLabel.Text = $"Целевой грид: {state.SelectedGridName}";
            SelectedGridLabel.Visible = true;
        }
        else
        {
            SelectedGridLabel.Visible = false;
        }
    }

    private void UpdateRadar(BSAConsoleUiState state)
    {
        if (state.RadarState != null)
        {
            RadarScreen.UpdateState(state.RadarState);
        }
    }

    private void UpdateMapView(BSAConsoleUiState state)
    {
        if (state.SelectedGridUid != null && _isMapMode)
        {
            var gridEntity = _entMan.GetEntity(state.SelectedGridUid.Value);
            if (MapScreen.MapUid != gridEntity)
            {
                MapScreen.MapUid = gridEntity;
                MapScreen.ForceNavMapUpdate();
            }
        }
    }

    private void UpdateDisk(BSAConsoleUiState state)
    {
        if (state.HasDisk)
        {
            DiskStatusLabel.Text = $"Сектор: {state.TargetMapName ?? "Неизвестный"}";
            DiskStatusLabel.FontColorOverride = Color.FromHex("#00FF00");
            EjectDiskButton.Visible = true;

            ModeStationGrid.Disabled = false;

            CustomGridsContainer.RemoveAllChildren();
            foreach (var grid in state.AvailableGrids)
            {
                var btn = new Button
                {
                    Text = grid,
                    TextAlign = Label.AlignMode.Left,
                    MinHeight = 28,
                };
                var capturedGrid = grid;
                btn.OnPressed += _ =>
                {
                    OnSelectGridPressed?.Invoke(capturedGrid);
                    _viewDropdownOpen = false;
                    ViewDropdownPanel.Visible = false;
                };
                CustomGridsContainer.AddChild(btn);
            }
        }
        else
        {
            DiskStatusLabel.Text = "Вставьте координатный диск";
            DiskStatusLabel.FontColorOverride = Color.FromHex("#FFaa00");
            EjectDiskButton.Visible = false;

            ModeStationGrid.Disabled = true;

            CustomGridsContainer.RemoveAllChildren();
        }
    }

    private void UpdateLogs(BSAConsoleUiState state)
    {
        LogContainer.RemoveAllChildren();

        foreach (var entry in state.LogEntries)
        {
            var label = new Label
            {
                Text = entry,
                FontColorOverride = GetLogColor(entry),
                HorizontalExpand = true,
                Margin = new Thickness(0, 1),
            };
            LogContainer.AddChild(label);
        }
    }

    private Color GetLogColor(string entry)
    {
        if (entry.Contains("[СЕТЬ]") || entry.Contains("[ДИСК]"))
            return Color.FromHex("#00d4ff");
        if (entry.Contains("[НАВИГАЦИЯ]"))
            return Color.FromHex("#FFaa00");
        if (entry.Contains("[ЗАЛП]"))
            return Color.FromHex("#FF4444");
        if (entry.Contains("[ЛОГ]") && entry.Contains("Охлаждение завершено"))
            return Color.FromHex("#00FF00");
        if (entry.Contains("[ЛОГ]"))
            return Color.FromHex("#FF8800");
        if (entry.Contains("[ОШИБКА]"))
            return Color.FromHex("#FF4444");
        return Color.FromHex("#CCCCCC");
    }

    private void ToggleViewDropdown()
    {
        _viewDropdownOpen = !_viewDropdownOpen;
        ViewDropdownPanel.Visible = _viewDropdownOpen;
    }

    private void SelectViewMode(string mode)
    {
        _viewDropdownOpen = false;
        ViewDropdownPanel.Visible = false;
        OnSwitchViewPressed?.Invoke(mode);
    }

    private void OnRadarClicked(EntityCoordinates coords)
    {
        CoordinateX.Text = $"{coords.X:F1}";
        CoordinateY.Text = $"{coords.Y:F1}";
    }

    private void OnMapClicked(MapCoordinates mapPos)
    {
        CoordinateX.Text = $"{mapPos.X:F1}";
        CoordinateY.Text = $"{mapPos.Y:F1}";
    }

    private float GetX()
    {
        if (float.TryParse(CoordinateX.Text, System.Globalization.NumberStyles.Float,
                System.Globalization.CultureInfo.InvariantCulture, out var x))
            return x;
        return 0f;
    }

    private float GetY()
    {
        if (float.TryParse(CoordinateY.Text, System.Globalization.NumberStyles.Float,
                System.Globalization.CultureInfo.InvariantCulture, out var y))
            return y;
        return 0f;
    }
}
