using Content.Client.UserInterface.Controls;
using Content.Shared.DeadSpace.PipeShuttle;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.PipeShuttle.UI;

[GenerateTypedNameReferences]
public sealed partial class PipeShuttleWindow : FancyWindow
{
    private int _selectedIndex = -1;

    public event Action<string>? OnDestSelected;

    public PipeShuttleWindow()
    {
        RobustXamlLoader.Load(this);

        CallButton.OnPressed += _ =>
        {
            if (_selectedIndex >= 0 && StopList.Count > _selectedIndex)
            {
                var item = StopList[_selectedIndex];
                if (item.Metadata is string destId)
                    OnDestSelected?.Invoke(destId);
            }
        };

        StopList.OnItemSelected += args =>
        {
            _selectedIndex = args.ItemIndex;
            CallButton.Disabled = false;
        };
    }

    public void UpdateState(PipeShuttleUiState state)
    {
        StopList.Clear();
        _selectedIndex = -1;
        CallButton.Disabled = true;

        foreach (var dest in state.Destinations)
        {
            var label = dest.Name;
            if (state.CurrentDestId == dest.Id)
                label += " (уже здесь)";
            else if (state.Travelling && state.TargetDestId == dest.Id)
                label += " (прибываем)";

            StopList.AddItem(label, metadata: dest.Id);
        }

        if (state.Travelling)
        {
            var targetName = state.TargetDestId;
            foreach (var d in state.Destinations)
            {
                if (d.Id == state.TargetDestId)
                {
                    targetName = d.Name;
                    break;
                }
            }
            StatusLabel.Text = $"Статус: Направляемся {targetName}";
            CallButton.Disabled = true;
        }
        else if (state.CurrentDestId != null)
        {
            var currentName = state.CurrentDestId;
            foreach (var d in state.Destinations)
            {
                if (d.Id == state.CurrentDestId)
                {
                    currentName = d.Name;
                    break;
                }
            }
            StatusLabel.Text = $"Статус: Пристыкованы {currentName}";
        }
        else
        {
            StatusLabel.Text = "Статус: Простаиваем";
        }
    }
}
