using Content.Client.UserInterface.Controls;
using Content.Shared.Tram.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Tram.UI;

[GenerateTypedNameReferences]
public sealed partial class TramConsoleWindow : FancyWindow
{
    public event Action<string>? DestinationSelected;

    private string? _selectedDestinationId;

    public TramConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        SendButton.OnPressed += OnSendPressed;
    }

    private void OnSendPressed(BaseButton.ButtonEventArgs args)
    {
        if (_selectedDestinationId != null)
        {
            DestinationSelected?.Invoke(_selectedDestinationId);
        }
    }

    public void UpdateState(TramConsoleBoundUserInterfaceState state)
    {
        if (state.IsBroken)
        {
            StatusLabel.Text = "BROKEN - No Tram Detected";
            StatusLabel.FontColorOverride = Color.Red;
            LocationLabel.Text = "N/A";
            SendButton.Disabled = true;
            DestinationsContainer.RemoveAllChildren();
            return;
        }

        if (state.IsMoving)
        {
            StatusLabel.Text = "MOVING";
            StatusLabel.FontColorOverride = Color.Green;
            SendButton.Disabled = true;
        }
        else if (state.ControlsLocked)
        {
            StatusLabel.Text = "CONTROLS LOCKED";
            StatusLabel.FontColorOverride = Color.Yellow;
            SendButton.Disabled = true;
        }
        else
        {
            StatusLabel.Text = "READY";
            StatusLabel.FontColorOverride = Color.White;
            SendButton.Disabled = _selectedDestinationId == null;
        }

        // Find current location name
        string currentName = "In Transit";
        if (state.CurrentLocation != null)
        {
            var currentDest = state.Destinations.Find(d => d.Id == state.CurrentLocation);
            if (currentDest != null)
            {
                currentName = currentDest.Name;
            }
        }
        LocationLabel.Text = currentName;

        // Rebuild destination buttons
        DestinationsContainer.RemoveAllChildren();
        _selectedDestinationId = null;

        var group = new ButtonGroup();

        foreach (var dest in state.Destinations)
        {
            var btn = new Button
            {
                Text = dest.Name,
                HorizontalExpand = true,
                Margin = new Thickness(2),
                Group = group,
                ToggleMode = true,
            };

            // Highlight current location
            if (dest.IsHere)
            {
                btn.Text = $">> {dest.Name} (Current)";
                btn.Disabled = true;
            }

            var destId = dest.Id;
            btn.OnPressed += args =>
            {
                _selectedDestinationId = destId;
                SendButton.Disabled = false;
            };

            DestinationsContainer.AddChild(btn);
        }
    }
}
