// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System.Numerics;
using Content.Shared.DeadSpace.AntagGearSelector;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.DeadSpace.AntagGearSelector;

[GenerateTypedNameReferences]
public sealed partial class AntagGearSelectorWindow : DefaultWindow
{
    public event Action<int, int>? OnConfirmed;
    private int _gearIndex = -1;
    private int _perkIndex = -1;
    private AntagGearSelectorOption? _selectedGear;
    private readonly ButtonGroup _gearGroup = new();
    private readonly ButtonGroup _perkGroup = new();
    private readonly IGameTiming _timing;
    private TimeSpan _deadline;

    public AntagGearSelectorWindow()
    {
        RobustXamlLoader.Load(this);
        _timing = IoCManager.Resolve<IGameTiming>();
        Title = "Выбор специализации";
        ConfirmButton.OnPressed += _ => OnConfirmed?.Invoke(_gearIndex, _perkIndex);
    }

    public void UpdateState(AntagGearSelectorEuiState state)
    {
        GearContainer.RemoveAllChildren();
        PerksContainer.RemoveAllChildren();
        _deadline = state.Deadline;
        AddGearOptions(state.Gear);
    }

    private void AddGearOptions(List<AntagGearSelectorOption> options)
    {
        foreach (var option in options)
            AddOption(GearContainer, option.Index, option.Name, option.Description, option.SpritePrototype, option);
    }

    private void AddPerkOptions(List<AntagGearSelectorPerkOption> options)
    {
        foreach (var option in options)
            AddOption(PerksContainer, option.Index, option.Name, option.Description, option.SpritePrototype, null);
    }

    private void AddOption(BoxContainer container, int index, string name, string description,
        string spritePrototype, AntagGearSelectorOption? gear)
    {
        var button = new ContainerButton
        {
            HorizontalExpand = true,
            MinHeight = 64,
            ToggleMode = true,
            ToolTip = description,
            Group = gear == null ? _perkGroup : _gearGroup,
        };

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 8,
            Margin = new Thickness(4),
            MouseFilter = Control.MouseFilterMode.Ignore,
        };
        var preview = new EntityPrototypeView
        {
            SetSize = new Vector2(48, 48),
            MouseFilter = Control.MouseFilterMode.Ignore,
        };
        preview.SetPrototype(spritePrototype);
        row.AddChild(preview);
        row.AddChild(new Label
        {
            Text = $"{name}\n{description}",
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            MouseFilter = Control.MouseFilterMode.Ignore,
        });
        button.AddChild(row);

        button.OnPressed += _ =>
        {
            foreach (var child in container.Children)
            {
                if (child is ContainerButton other)
                    other.Pressed = false;
            }
            button.Pressed = true;

            if (gear != null)
            {
                _gearIndex = index;
                _selectedGear = gear;
                SelectedLabel.Text = $"Выбран боец: {name}. Выберите перк.";
                _perkIndex = -1;
                PerksContainer.RemoveAllChildren();
                AddPerkOptions(gear.Perks);
            }
            else
            {
                _perkIndex = index;
                SelectedLabel.Text = $"Выбраны: {_selectedGear?.Name} — {name}";
            }

            ConfirmButton.Disabled = _gearIndex < 0 || (_selectedGear?.Perks.Count > 0 && _perkIndex < 0);
        };
        container.AddChild(button);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        var remaining = _deadline - _timing.CurTime;
        if (remaining < TimeSpan.Zero)
            remaining = TimeSpan.Zero;
        TimerLabel.Text = $"До случайного выбора: {remaining.Minutes:00}:{remaining.Seconds:00}";
    }
}
