// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System.Linq;
using Robust.Shared.Audio;
using Content.Client.Decals.UI;
using Content.Client.DeadSpace.Stylesheets;
using Content.Shared.Corvax.TTS;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Content.Shared.DeadSpace.Languages.Prototypes;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Audio;
using Robust.Client.ResourceManagement;
using Robust.Shared.Audio.Sources;
using Content.Shared.Communications;

namespace Content.Client.Communications.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class EmagCommunicationsInterface : FancyWindow
    {
        [Dependency] private readonly ILocalizationManager _localization = default!;
        [Dependency] private readonly IPrototypeManager _protoManager = default!;
        [Dependency] private readonly IAudioManager _clydeAudio = default!;
        [Dependency] private readonly IResourceCache _resource = default!;

        private readonly List<TTSVoicePrototype> _voices; // Corvax-TTS
        private readonly List<LanguagePrototype> _languages; // DS14-Languages
        private readonly SoundCollectionSpecifier _soundsCollectionSpecifier = new("SoundAnnoceCollection");
        private readonly SoundCollectionPrototype _soundsProto;
        public Action<string>? OnVoiceChange; // Corvax-TTS
        private readonly ProtoId<LanguagePrototype> _firstLanguageId = "GeneralLanguage"; // DS14-Languages

        // DS14-announce-start
        private LineEdit? _colorHexEdit;
        private Button? _colorPreviewBtn;
        private PaletteColorPicker? _colorPalette;
        private LineEdit? _senderEdit;
        private const int MaxSenderLength = 32;

        private const int ColorShortLength = 3;
        private const int ColorLongLength = 6;
        private ProtoId<LanguagePrototype> _choosenID = default!;
        private string _choosenIDVoice = "";
        private string _choosenSoundPath = "/Audio/_DeadSpace/Announcements/centcomm.ogg";


        private IAudioSource? _audioStreamTest;
        // DS14-announce-end

        // Публичные начинаются
        public bool HavePassword = false;
        public event Action<string>? OnInputPassword;
        public event Action<EmagedAnonce>? OnOutputMessage;
        public int MaxPassWordLenght = 10;

        public EmagCommunicationsInterface()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            // DS14-announce-start
            _colorHexEdit = SafeFind<LineEdit>("ColorHex", c => c.OnTextChanged += OnColorTextChanged);
            _colorPreviewBtn = SafeFind<Button>("ColorPreview", c => c.OnPressed += OnColorPreviewPressed);
            _senderEdit = SafeFind<LineEdit>("Sender", c => c.OnTextChanged += OnSenderChanged);

            AddDs14OptionStyles(VoiceSelector, LanguageSelector, MusicSelector);
            MusicSelector.OnItemSelected += OnSelect;
            VoiceSelector.Filterable = true;
            CenterButtonText(AnnounceButton);
            CustomTTS.Label.AddStyleClass(DeadSpaceMenuSheetlet.ProfileLabel);
            UpdateColorPreview();
            // DS14-announce-end
            Announcement.Placeholder = new Rope.Leaf(_localization.GetString("admin-announce-announcement-placeholder"));
            VoiceSelector.OnItemSelected += AnnounceMethodOnOnTTSItemSelected;
            LanguageSelector.OnItemSelected += AnnounceMethodOnLanguageSelected; // DS14-Languages
            Announcement.OnKeyBindUp += AnnouncementOnOnTextChanged;
            PreviewButton.OnPressed += PreviewButtonWorks;
            RightPanelConfirmButton.OnPressed += CookingPassword;
            AnnounceButton.OnPressed += SendEmagedMessage;

            RightPanelInput.OnTextChanged += (args) =>
            {
                var currentLength = args.Control.Text.Length;
                if (currentLength == 0)
                {
                    // Состояние 1: Пустой ввод
                    RightPanelConfirmButton.Disabled = true;
                    RightPanelConfirmButton.ToolTip = Loc.GetString("comms-console-message-too-long"); // Или более подходящий тултип для пустого поля
                }
                else if (currentLength > MaxPassWordLenght)
                {
                    // Состояние 2: Слишком длинный ввод (это и есть ваша проверка, но теперь она в начале)
                    RightPanelConfirmButton.Disabled = true;
                    RightPanelConfirmButton.ToolTip = Loc.GetString("comms-console-message-too-long");
                }
                else
                {
                    // Состояние 3: Длина находится в пределах [1, MaxPassWordLenght] - все ОК
                    RightPanelConfirmButton.Disabled = false;
                    RightPanelConfirmButton.ToolTip = null;
                }
            };

            // Corvax-TTS-Start
            _voices = _protoManager // DS14-Languages
                .EnumeratePrototypes<TTSVoicePrototype>()
                .OrderBy(o => Loc.GetString(o.Name))
                .ToList();
            for (var i = 0; i < _voices.Count; i++)
            {
                var name = Loc.GetString(_voices[i].Name);
                VoiceSelector.AddItem(name);
                VoiceSelector.SetItemMetadata(i, _voices[i].ID);
            }
            // Corvax-TTS-End

            // DS14-Languages-start
            _languages = _protoManager.EnumeratePrototypes<LanguagePrototype>()
                .OrderBy(o => Loc.GetString(o.Name))
                .ToList();

            var defaultLanguage = _languages.FirstOrDefault(l => l.ID == _firstLanguageId);
            if (defaultLanguage != null)
            {
                _languages.Remove(defaultLanguage);
                _languages.Insert(0, defaultLanguage);
            }

            for (var i = 0; i < _languages.Count; i++)
            {
                var name = Loc.GetString(_languages[i].Name);
                LanguageSelector.AddItem(name);
                LanguageSelector.SetItemMetadata(i, _languages[i].ID);
            }
            // DS14-Languages-end
            if (_soundsCollectionSpecifier.Collection != null)
            {
                _soundsProto = _protoManager.Index<SoundCollectionPrototype>(_soundsCollectionSpecifier.Collection);
                for (var i = 0; i < _soundsProto.PickFiles.Count; i++)
                {
                    MusicSelector.AddItem(_soundsProto.PickFiles[i].CanonPath);
                    MusicSelector.SetItemMetadata(i, new ResPath(_soundsProto.PickFiles[i].CanonPath));
                }
            }
            else
            {
                throw new Exception($"EmagCommunicationsInterface не смог найти привязанную к нему коллекцию звуков");
            }
            if (HavePassword)
            {
                RightPanelInput.Visible = false;
                RightPanelConfirmButton.Visible = false;
            }
            else
            {
                RightPanelInput.Visible = true;
                RightPanelConfirmButton.Visible = true;
            }
            VoiceSelector.Select(0);
            LanguageSelector.Select(0);
        }

        // DS14-announce-start
        private T? SafeFind<T>(string name, Action<T>? init = null) where T : Control
        {
            var ctrl = FindControl<T>(name);
            if (ctrl == null)
            {
                Logger.Warning($"AdminAnnounceWindow: control '{name}' not found.");
                return null;
            }

            init?.Invoke(ctrl);
            return ctrl;
        }

        private void OnColorTextChanged(LineEdit.LineEditEventArgs args)
        {
            if (_colorHexEdit == null) return;

            var t = _colorHexEdit.Text.Trim();
            if (t.StartsWith('#'))
                t = t[1..];

            t = new string(t.Where(Uri.IsHexDigit).ToArray());
            if (t.Length > ColorLongLength)
                t = t[..ColorLongLength];

            if (_colorHexEdit.Text != t)
                _colorHexEdit.Text = t;

            UpdateColorPreview();
        }

        private void UpdateColorPreview()
        {
            if (_colorPreviewBtn == null)
                return;

            if (!TryGetPreviewColor(out var color))
            {
                _colorPreviewBtn.StyleBoxOverride = BuildColorPreviewStyle(Color.FromHex("#0b1118"));
                return;
            }

            _colorPreviewBtn.StyleBoxOverride = BuildColorPreviewStyle(color);
        }

        private bool TryGetPreviewColor(out Color color)
        {
            color = default;
            if (_colorHexEdit == null)
                return false;

            var t = _colorHexEdit.Text.Trim();
            if (t.Length != ColorShortLength && t.Length != ColorLongLength)
                return false;

            try
            {
                color = Color.FromHex("#" + t);
                return true;
            }
            catch
            {
                return false;
            }
        }

        private StyleBoxFlat BuildColorPreviewStyle(Color color)
        {
            return new StyleBoxFlat
            {
                BackgroundColor = color,
                BorderColor = Color.FromHex("#3b4e60"),
                BorderThickness = new Thickness(1),
            };
        }

        private void OnColorPreviewPressed(BaseButton.ButtonEventArgs args)
        {
            if (_colorHexEdit == null)
                return;

            if (_colorPalette == null)
            {
                _colorPalette = new PaletteColorPicker();
                _colorPalette.PaletteList.OnItemSelected += OnPaletteColorSelected;
                _colorPalette.OpenCenteredLeft();
                return;
            }

            if (_colorPalette.IsOpen)
                _colorPalette.Close();
            else
                _colorPalette.Open();
        }

        private void OnPaletteColorSelected(ItemList.ItemListSelectedEventArgs args)
        {
            if (_colorHexEdit == null)
                return;

            var selected = args.ItemList.GetSelected().FirstOrDefault();
            if (selected?.Metadata is not Color color)
                return;

            _colorHexEdit.Text = color.ToHexNoAlpha().TrimStart('#');
            UpdateColorPreview();
        }

        private void OnSenderChanged(LineEdit.LineEditEventArgs args)
        {
            if (_senderEdit == null) return;

            var t = new string(_senderEdit.Text.Where(c => !char.IsControl(c)).ToArray());
            if (t.Length > MaxSenderLength)
                t = t[..MaxSenderLength];
            if (_senderEdit.Text != t)
                _senderEdit.Text = t;
        }

        private void AddDs14OptionStyles(params OptionButton[] options)
        {
            foreach (var option in options)
            {
                option.AddStyleClass(DeadSpaceMenuSheetlet.ProfileControl);
                if (!option.OptionStyleClasses.Contains(DeadSpaceMenuSheetlet.ProfileControl))
                    option.OptionStyleClasses.Add(DeadSpaceMenuSheetlet.ProfileControl);
            }
        }

        private void CenterButtonText(Button button)
        {
            button.TextAlign = Label.AlignMode.Center;
            button.Label.HorizontalExpand = true;
            button.Label.HorizontalAlignment = HAlignment.Stretch;
            button.Label.Align = Label.AlignMode.Center;
        }

        private void CenterOptionButtonText(Control control)
        {
            if (control is Label label &&
                label.StyleClasses.Contains(OptionButton.StyleClassOptionButton))
            {
                label.HorizontalExpand = true;
                label.Align = Label.AlignMode.Center;
                return;
            }

            foreach (var child in control.Children)
            {
                CenterOptionButtonText(child);
            }
        }

        private void CenterNestedButtonText(Control control)
        {
            if (control is Button button)
                CenterButtonText(button);

            foreach (var child in control.Children)
            {
                CenterNestedButtonText(child);
            }
        }
        // DS14-announce-end

        private void AnnouncementOnOnTextChanged(GUIBoundKeyEventArgs args)
        {
            AnnounceButton.Disabled = Rope.Collapse(Announcement.TextRope).TrimStart() == "";
        }

        // Corvax-TTS-Start
        private void AnnounceMethodOnOnTTSItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            VoiceSelector.SelectId(args.Id);
            if (args.Button.SelectedMetadata != null && args.Button.SelectedMetadata is string)
            {
                _choosenIDVoice = (string)args.Button.SelectedMetadata;
            }
        }
        // Corvax-TTS-End

        // DS14-Languages-start
        private void AnnounceMethodOnLanguageSelected(OptionButton.ItemSelectedEventArgs args)
        {
            LanguageSelector.SelectId(args.Id);
            if (args.Button.SelectedMetadata != null && args.Button.SelectedMetadata is ProtoId<LanguagePrototype>)
            {
                _choosenID = (ProtoId<LanguagePrototype>)args.Button.SelectedMetadata;
            }
        }

        public string ColorHexText
        {
            get
            {
                var t = _colorHexEdit?.Text.Trim() ?? "";
                return (t.Length == ColorShortLength || t.Length == ColorLongLength) ? t : "";
            }
        }
        public string SenderText => _senderEdit?.Text ?? "";

        public override void Close()
        {
            _colorPalette?.Close();
            if (_audioStreamTest != null)
                _audioStreamTest.StopPlaying();
            base.Close();
        }
        private void OnSelect(OptionButton.ItemSelectedEventArgs args)
        {
            MusicSelector.Select(args.Id);
            if (args.Button.SelectedMetadata is ResPath && _resource.TryGetResource<AudioResource>((ResPath)args.Button.SelectedMetadata, out var audio))
            {
                _choosenSoundPath = ((ResPath)args.Button.SelectedMetadata).ToString();
                if (_audioStreamTest != null && _audioStreamTest.Playing)
                {
                    _audioStreamTest.StopPlaying();
                    _audioStreamTest.Dispose();
                    PreviewButton.Text = "▶";
                }
                _audioStreamTest = _clydeAudio.CreateAudioSource(audio.AudioStream);
                MusicDurationLabel.Text = audio.AudioStream.Length.ToString(@"mm\:ss");
            }
        }
        private void PreviewButtonWorks(BaseButton.ButtonEventArgs args)
        {
            if (_audioStreamTest == null)
                return;
            _audioStreamTest.Global = true;
            if (PreviewButton.Text == "▶")
            {
                _audioStreamTest.StartPlaying();
                PreviewButton.Text = "■";
            }
            else
            {
                _audioStreamTest.StopPlaying();
                PreviewButton.Text = "▶";
            }
        }

        private void CookingPassword(BaseButton.ButtonEventArgs args)
        {
            if (RightPanelInput.Text == null)
                return;
            OnInputPassword?.Invoke(RightPanelInput.Text);
        }
        private void SendEmagedMessage(BaseButton.ButtonEventArgs args)
        {
            if (!HavePassword)
            {
                OnOutputMessage?.Invoke(new EmagedAnonce(Sender.Text,
                Rope.Collapse(Announcement.TextRope),
                _choosenID,
                CustomTTS.ToggleMode,
                _choosenIDVoice,
                Announcer.Text,
                ColorHex.Text,
                _choosenSoundPath, password: RightPanelInput.Text));
            }
            else
            {
                OnOutputMessage?.Invoke(new EmagedAnonce(Sender.Text,
                Rope.Collapse(Announcement.TextRope),
                _choosenID,
                CustomTTS.ToggleMode,
                _choosenIDVoice,
                Announcer.Text,
                ColorHex.Text,
                _choosenSoundPath));
            }
        }
    }
}
