- type: entity
  id: CrateFlowers
  parent: CrateGenericSteel
  name: ящик искусственных цветов
  description: Ящик полный искусственных цветов
  components:
  - type: StorageFill
    contents:
    - id: RedFlower
      amount: 5
    - id: DarkFlower
      amount: 5
    - id: PinkFlower
      amount: 5
    - id: WhiteFlower
      amount: 5
    - id: YellowFlower
      amount: 5
    - id: PurpleFlower
      amount: 5
