// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Robust.Client.UserInterface.XAML;
using Content.Client.UserInterface.Controls;
using Content.Shared.DeadSpace.EnergySeller;
using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;

namespace Content.Client.DeadSpace.EnergySeller;

[GenerateTypedNameReferences]
public sealed partial class EnergySellerUserInterface : FancyWindow
{
    public event Action<Dictionary<int, string>>? OnConfirmSellLimit;
    public event Action<Dictionary<int, string>>? OnConfirmSpeedCharge;
    public EnergySellerUserInterface()
    {
        RobustXamlLoader.Load(this);
        ChargeSpeedSlider.OnValueChanged += (args) => ChargeSpeedValue.Text = args.Value.ToString();
        MaxChargeSlider.OnValueChanged += (args) => LimitSellValue.Text = args.Value.ToString();
        ChargeSpeedMaxLabel.Text = ChargeSpeedSlider.Value.ToString();
        MaxChargeMaxLabel.Text = MaxChargeSlider.Value.ToString();
        SellLimitConfirm.OnPressed += _ => OnConfirmSellLimit?.Invoke(new Dictionary<int, string>() { { 2, MaxChargeLineEdit.Text }, { 1, MaxChargeSlider.Value.ToString() } });
        SpeedChargeConfirm.OnPressed += _ => OnConfirmSpeedCharge?.Invoke(new Dictionary<int, string>() { { 2, ChargeSpeedLineEdit.Text }, { 1, ChargeSpeedSlider.Value.ToString() } });
    }
    public void UpdateState(BoundUserInterfaceState state)
    {
        var castState = (EnergySellerBoundUserInterfaceState)state;
        ChargeSpeedSlider.MaxValue = castState.MaxChargeRate;
        ChargeSpeedSlider.Value = castState.NowChargeRate;
        ChargeSpeedValue.Text = castState.NowChargeRate.ToString();
        ChargeSpeedMaxLabel.Text = castState.MaxChargeRate.ToString();
        MaxChargeSlider.MaxValue = castState.MaxLimit;
        MaxChargeSlider.Value = castState.NowLimit;
        MaxChargeMaxLabel.Text = castState.MaxLimit.ToString();
        LimitSellValue.Text = castState.NowLimit.ToString();
    }
}
