using Robust.Client.UserInterface.XAML;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;

namespace Content.Client.DeadSpace.EnergySeller;

[GenerateTypedNameReferences]
public sealed partial class EnergySellerUserInterface : FancyWindow
{
    public EnergySellerUserInterface()
    {
        RobustXamlLoader.Load(this);
    }
}
