using Robust.Client.UserInterface.XAML;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using System.Linq;

namespace Content.Client.DeadSpace.EnergySeller;

[GenerateTypedNameReferences]
public sealed partial class EnergySellerUserInterface : FancyWindow
{
    public event Action<Dictionary<int, string>>? OnConfirmSellLimit;
    public event Action<Dictionary<int, string>>? OnConfirmSpeedCharge;
    public EnergySellerUserInterface()
    {
        RobustXamlLoader.Load(this);
        MaxChargeLineEdit.OnTextChanged += (args) =>
            {
                if (args.Control.Text.Count() > 0)
                {
                    SellLimitConfirm.Disabled = false;
                }
                else if (int.TryParse(args.Text, out int chargeint) && chargeint >= 5000)
                {
                    SellLimitConfirm.Disabled = false;
                }
                else
                {
                    SellLimitConfirm.Disabled = true;
                }
            };
        ChargeSpeedLineEdit.OnTextChanged += (args) =>
            {
                if (args.Control.Text.Count() > 0)
                {
                    SpeedChargeConfirm.Disabled = false;
                }
                else if (int.TryParse(args.Text, out int chargeint) && chargeint >= 5000)
                {
                    SpeedChargeConfirm.Disabled = false;
                }
                else
                {
                    SpeedChargeConfirm.Disabled = true;
                }
            };
        ChargeSpeedSlider.OnValueChanged += (args) => ChargeSpeedValue.Text = args.Value.ToString();
        MaxChargeSlider.OnValueChanged += (args) => LimitSellValue.Text = args.Value.ToString();
        ChargeSpeedMaxLabel.Text = ChargeSpeedSlider.Value.ToString();
        MaxChargeMaxLabel.Text = MaxChargeSlider.Value.ToString();
        SellLimitConfirm.OnPressed += _ => OnConfirmSellLimit?.Invoke(new Dictionary<int, string>() { { 1, MaxChargeLineEdit.Text }, { 2, MaxChargeSlider.Value.ToString() } });
        SpeedChargeConfirm.OnPressed += _ => OnConfirmSpeedCharge?.Invoke(new Dictionary<int, string>() { { 1, ChargeSpeedLineEdit.Text }, { 2, ChargeSpeedSlider.Value.ToString() }});
    }
    public void SetMaxSlider(int charge, int limit)
    {
        ChargeSpeedSlider.MaxValue = charge;
        ChargeSpeedMaxLabel.Text = charge.ToString();
        MaxChargeMaxLabel.Text = limit.ToString();
        MaxChargeSlider.MaxValue = limit;
    }
    public void SetBattarycomp(int charge, int limit)
    {
        ChargeSpeedSlider.Value = charge;
        ChargeSpeedValue.Text = charge.ToString();
        MaxChargeSlider.Value = limit;
        LimitSellValue.Text = limit.ToString();
    }
}
