using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.CharacterFlavor;

[GenerateTypedNameReferences]
public sealed partial class HeadshotExamineWindow : FancyWindow
{
    private readonly HeadshotUIController _controller;

    public HeadshotExamineWindow(HeadshotUIController controller)
    {
        RobustXamlLoader.Load(this);
        _controller = controller;
    }

    public void SetHeadshotTexture(OwnedTexture texture)
    {
        HeadshotLoadingLabel.Visible = false;
        HeadshotTexture.Texture = texture;
        HeadshotTexture.Visible = true;
        HeadshotContainer.Visible = true;
    }

    public void SetFlavorText(string flavorText)
    {
        if (string.IsNullOrWhiteSpace(flavorText))
        {
            FlavorTextLabel.SetMessage(Loc.GetString("headshot-no-flavor-text"));
            return;
        }
        FlavorTextLabel.Text = flavorText;
    }

    public void ShowLoading()
    {
        HeadshotContainer.Visible = true;
        HeadshotTexture.Visible = false;
        HeadshotLoadingLabel.Visible = true;
    }

    public void HideLoading()
    {
        HeadshotLoadingLabel.Visible = false;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
        {
            if (HeadshotTexture.Texture is OwnedTexture owned)
                owned.Dispose();
        }
    }
}
