using System.IO;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.DeadSpace.CharacterFlavor;

[GenerateTypedNameReferences]
public sealed partial class HeadshotPanel : Control
{
    public Action<string?>? OnHeadshotDataChanged;
    public Action<string>? OnUrlDownloadRequested;

    private OwnedTexture? _previewTexture;

    public HeadshotPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DownloadUrlButton.OnPressed += _ => OnDownloadUrl();
        ApplyBase64Button.OnPressed += _ => OnApplyBase64();
        ClearHeadshotButton.OnPressed += _ => OnClearHeadshot();
    }

    private void OnDownloadUrl()
    {
        var url = HeadshotUrlInput.Text.Trim();
        if (string.IsNullOrWhiteSpace(url))
            return;

        if (!url.StartsWith("http://", StringComparison.OrdinalIgnoreCase) &&
            !url.StartsWith("https://", StringComparison.OrdinalIgnoreCase))
        {
            UrlStatusLabel.Text = Loc.GetString("headshot-invalid-url");
            return;
        }

        UrlStatusLabel.Text = Loc.GetString("headshot-downloading");
        OnUrlDownloadRequested?.Invoke(url);
    }

    private void OnApplyBase64()
    {
        var base64 = Rope.Collapse(HeadshotBase64Input.TextRope).Trim();
        if (string.IsNullOrWhiteSpace(base64))
            return;

        try
        {
            Convert.FromBase64String(base64);
            var dataUri = "data:image/png;base64," + base64;
            SetPreviewFromBase64(base64);
            OnHeadshotDataChanged?.Invoke(dataUri);
            Base64StatusLabel.Text = Loc.GetString("headshot-base64-applied");
        }
        catch
        {
            Base64StatusLabel.Text = Loc.GetString("headshot-invalid-base64");
        }
    }

    private void OnClearHeadshot()
    {
        ClearPreview();
        OnHeadshotDataChanged?.Invoke(null);
        HeadshotUrlInput.Text = string.Empty;
        HeadshotBase64Input.TextRope = Rope.Leaf.Empty;
        UrlStatusLabel.Text = string.Empty;
        Base64StatusLabel.Text = string.Empty;
    }

    public void SetHeadshotData(string? headshotData)
    {
        if (string.IsNullOrWhiteSpace(headshotData))
        {
            ClearPreview();
            return;
        }

        if (headshotData.StartsWith("data:image", StringComparison.OrdinalIgnoreCase))
        {
            var commaIndex = headshotData.IndexOf(',');
            if (commaIndex >= 0 && commaIndex < headshotData.Length - 1)
            {
                var base64 = headshotData[(commaIndex + 1)..];
                SetPreviewFromBase64(base64);
            }
        }
        else if (headshotData.StartsWith("http://", StringComparison.OrdinalIgnoreCase) ||
                 headshotData.StartsWith("https://", StringComparison.OrdinalIgnoreCase))
        {
            HeadshotUrlInput.Text = headshotData;
        }
    }

    public void SetPreviewFromBase64(string base64)
    {
        try
        {
            var bytes = Convert.FromBase64String(base64);
            var clyde = IoCManager.Resolve<Robust.Client.Graphics.IClyde>();
            using var stream = new MemoryStream(bytes);
            var texture = clyde.LoadTextureFromPNGStream(stream, "headshot-preview");

            _previewTexture?.Dispose();
            _previewTexture = texture;

            HeadshotPreview.Texture = texture;
            HeadshotPreview.Visible = true;
            NoHeadshotLabel.Visible = false;
        }
        catch
        {
        }
    }

    public void ClearPreview()
    {
        _previewTexture?.Dispose();
        _previewTexture = null;
        HeadshotPreview.Texture = null;
        HeadshotPreview.Visible = false;
        NoHeadshotLabel.Visible = true;
    }

    public void OnUrlDownloadCompleted(string? base64)
    {
        if (base64 != null)
        {
            SetPreviewFromBase64(base64);
            var dataUri = "data:image/png;base64," + base64;
            OnHeadshotDataChanged?.Invoke(dataUri);
            UrlStatusLabel.Text = Loc.GetString("headshot-download-success");
        }
        else
        {
            UrlStatusLabel.Text = Loc.GetString("headshot-download-failed");
        }
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
        {
            _previewTexture?.Dispose();
        }
    }
}
