using Content.Client.Message;
using Content.Shared.MassMedia.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NewsReaderUiFragment : BoxContainer
{
    public event Action? OnNextButtonPressed;
    public event Action? OnPrevButtonPressed;
    public event Action? OnNotificationSwithPressed;
    public event Action? OnLikeButtonPressed;
    public event Action? OnDislikeButtonPressed;
    public event Action<string>? OnSendCommentPressed;

    public NewsReaderUiFragment()
    {
        RobustXamlLoader.Load(this);

        Next.OnPressed += _ => OnNextButtonPressed?.Invoke();
        Prev.OnPressed += _ => OnPrevButtonPressed?.Invoke();
        NotificationSwitch.OnPressed += _ => OnNotificationSwithPressed?.Invoke();
        LikeButton.OnPressed += _ => OnLikeButtonPressed?.Invoke();
        DislikeButton.OnPressed += _ => OnDislikeButtonPressed?.Invoke();
        SendCommentButton.OnPressed += _ => OnSendCommentPressed?.Invoke(CommentInput.Text);
        CommentInput.OnTextEntered += _ => OnSendCommentPressed?.Invoke(CommentInput.Text);
    }

    public void UpdateState(NewsArticle article, int targetNum, int totalNum, bool notificationOn)
    {
        PageNum.Visible = true;
        PageText.Visible = true;
        ShareTime.Visible = true;
        Author.Visible = true;

        PageName.Text = article.Title;
        PageText.SetMarkupPermissive(article.Content);

        PageNum.Text = $"{targetNum}/{totalNum}";

        NotificationSwitch.Text = Loc.GetString(notificationOn ? "news-read-ui-notification-on" : "news-read-ui-notification-off");

        string shareTime = article.ShareTime.ToString(@"hh\:mm\:ss");
        ShareTime.SetMarkup(Loc.GetString("news-read-ui-time-prefix-text") + " " + shareTime);

        Author.SetMarkup(Loc.GetString("news-read-ui-author-prefix") + " " + (article.Author != null ? article.Author : Loc.GetString("news-read-ui-no-author")));

        Prev.Disabled = targetNum <= 1;
        Next.Disabled = targetNum >= totalNum;

        // Обновляем счетчики лайков/дизлайков
        LikeCount.Text = article.Likes.ToString();
        DislikeCount.Text = article.Dislikes.ToString();

        // Обновляем комментарии
        UpdateComments(article.Comments);
    }

    private void UpdateComments(List<NewsComment> comments)
    {
        CommentsContainer.DisposeAllChildren();

        if (comments.Count == 0)
        {
            var noCommentsLabel = new Label
            {
                Text = Loc.GetString("news-read-ui-no-comments"),
                Margin = new Thickness(4, 4, 4, 4)
            };
            CommentsContainer.AddChild(noCommentsLabel);
            return;
        }

        foreach (var comment in comments)
        {
            var commentPanel = new PanelContainer
            {
                Margin = new Thickness(0, 0, 0, 4),
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = new Color(0, 0, 0, 0.3f)
                }
            };

            var commentBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(4, 4, 4, 4)
            };

            var authorLabel = new RichTextLabel
            {
                Margin = new Thickness(0, 0, 0, 2)
            };
            authorLabel.SetMarkup(Loc.GetString("news-read-ui-comment-author", ("author", comment.Author ?? Loc.GetString("news-read-ui-anonymous")), ("time", comment.CommentTime.ToString(@"hh\:mm\:ss"))));

            var contentLabel = new RichTextLabel
            {
                Text = comment.Content
            };
            contentLabel.SetMarkupPermissive(comment.Content);

            commentBox.AddChild(authorLabel);
            commentBox.AddChild(contentLabel);
            commentPanel.AddChild(commentBox);
            CommentsContainer.AddChild(commentPanel);
        }
    }

    public void UpdateEmptyState(bool notificationOn)
    {
        PageNum.Visible = false;
        PageText.Visible = false;
        ShareTime.Visible = false;
        Author.Visible = false;

        PageName.Text = Loc.GetString("news-read-ui-not-found-text");

        NotificationSwitch.Text = Loc.GetString(notificationOn ? "news-read-ui-notification-on" : "news-read-ui-notification-off");

        // Очищаем комментарии в пустом состоянии
        CommentsContainer.DisposeAllChildren();
        LikeCount.Text = "0";
        DislikeCount.Text = "0";
    }
}
