using Content.Shared._Frostheim.Radar;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Frostheim.Radar;

[GenerateTypedNameReferences]
public sealed partial class FrostheimRadarWindow : DefaultWindow
{
    private static readonly Color PanelBg = Color.FromHex("#0a0e14");
    private static readonly Color HeaderBg = Color.FromHex("#0f1a24");
    private static readonly Color HeaderText = Color.FromHex("#7a9ab0");

    private RadarDisplayControl? _display;

    public FrostheimRadarWindow()
    {
        RobustXamlLoader.Load(this);

        MainPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = PanelBg,
            BorderColor = Color.FromHex("#1a2a3a"),
            BorderThickness = new Thickness(1),
        };

        HeaderPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = HeaderBg,
            BorderColor = Color.FromHex("#2a3a4a"),
            BorderThickness = new Thickness(0, 0, 0, 1),
        };

        HeaderLabel.FontColorOverride = HeaderText;

        _display = new RadarDisplayControl();
        RadarDisplay.AddChild(_display);
    }

    public void UpdateState(FrostheimRadarUpdateMessage state)
    {
        _display?.UpdateState(state);

        var total = state.TotalThrusters + state.TotalGyroscopes;
        Title = total > 0
            ? $":: РАДАР :: {total} ОБЪ."
            : ":: РАДАР :: НЕТ СИГНАЛА";
    }
}
