using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.RiotSign;

[GenerateTypedNameReferences]
public sealed partial class LabelWindow : DefaultWindow
{
    public string TypedText => LabelLineEdit.Text;

    public LabelWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
