// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.RedPhone;

[GenerateTypedNameReferences]
public sealed partial class RedPhoneReportWindow : DefaultWindow
{
    public event Action<string>? Submit;

    public RedPhoneReportWindow()
    {
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("red-phone-report-title");
        PromptLabel.Text = Loc.GetString("red-phone-report-prompt");

        MessageInput.OnTextChanged += _ => UpdateButtons();
        MessageInput.OnTextEntered += args => TrySubmit(args.Text);

        OkButton.OnPressed += _ => TrySubmit(MessageInput.Text);
        CancelButton.OnPressed += _ => Close();

        UpdateButtons();
    }

    private void TrySubmit(string message)
    {
        if (string.IsNullOrWhiteSpace(message))
            return;

        Submit?.Invoke(message.Trim());
    }

    private void UpdateButtons()
    {
        OkButton.Disabled = string.IsNullOrWhiteSpace(MessageInput.Text);
    }
}
