using System.Numerics;
using System.Text; // DS14
using System.Text.RegularExpressions; // DS14
using Content.Client.RichText;
using Content.Client.UserInterface.RichText;
using Content.Shared.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Timing; // DS14
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client.Paper.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class PaperWindow : BaseWindow
    {
        [Dependency] private readonly IInputManager _inputManager = default!;
        [Dependency] private readonly IResourceCache _resCache = default!;

        private static Color DefaultTextColor = new(25, 25, 25);

        // Size of resize handles around the paper.
        private const int DRAG_MARGIN_SIZE = 16;

        // We keep a reference to the paper content texture that we create
        // so that we can modify it later.
        private StyleBoxTexture _paperContentTex = new();

        // The number of lines that the content image represents.
        // See PaperVisualsComponent.ContentImageNumLines.
        private float _paperContentLineScale = 1.0f;

        // If paper limits the size in one or both axes, it'll affect whether
        // we're able to resize this UI or not. Default to everything enabled:
        private DragMode _allowedResizeModes = ~DragMode.None;

        public event Action<string>? OnSaved;

        private int _MaxInputLength = -1;

        public int MaxInputLength
        {
            get => _MaxInputLength;
            set
            {
                _MaxInputLength = value;
                UpdateFillState();
            }
        }

        // DS14-Start
        private bool _previewMode;

        private static readonly Regex HeadingWrapRegex = new(@"^\[head=[123]\]([\s\S]*)\[/head\]$");

        private DefaultWindow? _colorPickerWindow;

        // Color picker debounce: while dragging the sliders we only update the
        // swatch button. The text is rewritten once the user pauses for a moment,
        // so a single drag doesn't produce dozens of text edits.
        private const float ColorApplyDelay = 0.35f;
        private float _colorDebounceTimer;
        private bool _hasPendingColor;
        private Color _pendingColor;
        // DS14-End

        public PaperWindow()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            // We can't configure the RichTextLabel contents from xaml, so do it here:
            BlankPaperIndicator.SetMessage(Loc.GetString("paper-ui-blank-page-message"), null, DefaultTextColor);

            // Hook up the close button:
            CloseButton.OnPressed += _ => Close();

            Input.OnKeyBindDown += args => // Solution while TextEdit don't have events
            {
                if (args.Function == EngineKeyFunctions.MultilineTextSubmit)
                {
                    // SaveButton is disabled when we hit the max input limit. Just check
                    // that flag instead of trying to calculate the input length again
                    if (!SaveButton.Disabled)
                    {
                        RunOnSaved();
                        args.Handle();
                    }
                }
            };

            Input.OnTextChanged += _ =>
            {
                UpdateFillState();
                UpdatePreview(); // DS14
            };

            SaveButton.OnPressed += _ =>
            {
                RunOnSaved();
            };

            SaveButton.Text = Loc.GetString("paper-ui-save-button",
                ("keybind", _inputManager.GetKeyFunctionButtonString(EngineKeyFunctions.MultilineTextSubmit)));

            // DS14-Start
            BoldButton.OnPressed += _ => ToggleInlineFormat("[bold]", "[/bold]");
            ItalicButton.OnPressed += _ => ToggleInlineFormat("[italic]", "[/italic]");
            UnderlineButton.OnPressed += _ => ToggleInlineFormat("[uline]", "[/uline]");
            StrikeButton.OnPressed += _ => ToggleInlineFormat("[cut]", "[/cut]");
            MonoButton.OnPressed += _ => ToggleInlineFormat("[mono]", "[/mono]");
            SmallButton.OnPressed += _ => ToggleInlineFormat("[small=2]", "[/small]");
            ShiftButton.OnPressed += _ => ToggleInlineFormat("[shift]", "[/shift]");
            ConfusionButton.OnPressed += _ => ToggleInlineFormat("[conf=2]", "[/conf]");
            CyrillicConfusionButton.OnPressed += _ => ToggleInlineFormat("[сonf=2]", "[/сonf]");
            BulletButton.OnPressed += _ => ToggleBlockFormat("[bullet]", "[/bullet]");
            ColorButton.OnPressed += _ => ToggleColorPicker();

            FormatDropdown.AddItem(Loc.GetString("paper-ui-toolbar-text"));
            FormatDropdown.AddItem(Loc.GetString("paper-ui-toolbar-heading-1"));
            FormatDropdown.AddItem(Loc.GetString("paper-ui-toolbar-heading-2"));
            FormatDropdown.AddItem(Loc.GetString("paper-ui-toolbar-heading-3"));
            FormatDropdown.Select(0);
            FormatDropdown.OnItemSelected += args =>
            {
                var level = args.Id switch
                {
                    1 => (int?) 1,
                    2 => (int?) 2,
                    3 => (int?) 3,
                    _ => null,
                };
                ApplyHeading(level);
                FormatDropdown.Select(0);
            };

            PreviewToggleButton.OnPressed += _ =>
            {
                _previewMode = PreviewToggleButton.Pressed;
                Input.Visible = !_previewMode;
                PreviewLabel.Visible = _previewMode;
                if (_previewMode)
                {
                    PreviewToggleButton.Text = Loc.GetString("paper-ui-toolbar-edit");
                    UpdatePreview();
                }
                else
                {
                    PreviewToggleButton.Text = Loc.GetString("paper-ui-toolbar-preview");
                    Input.GrabKeyboardFocus();
                }
            }; // DS14-End
        }

        /// <summary>
        /// Initialize this UI according to <code>visuals</code> Initializes
        /// textures, recalculates sizes, and applies some layout rules.
        /// </summary>
        public void InitVisuals(EntityUid entity, PaperVisualsComponent visuals)
        {
            // Initialize the background:
            PaperBackground.ModulateSelfOverride = visuals.BackgroundModulate;
            var backgroundImage = visuals.BackgroundImagePath != null ? _resCache.GetResource<TextureResource>(visuals.BackgroundImagePath) : null;
            if (backgroundImage != null)
            {
                var backgroundImageMode = visuals.BackgroundImageTile ? StyleBoxTexture.StretchMode.Tile : StyleBoxTexture.StretchMode.Stretch;
                var backgroundPatchMargin = visuals.BackgroundPatchMargin;
                PaperBackground.PanelOverride = new StyleBoxTexture
                {
                    Texture = backgroundImage,
                    TextureScale = visuals.BackgroundScale,
                    Mode = backgroundImageMode,
                    PatchMarginLeft = backgroundPatchMargin.Left,
                    PatchMarginBottom = backgroundPatchMargin.Bottom,
                    PatchMarginRight = backgroundPatchMargin.Right,
                    PatchMarginTop = backgroundPatchMargin.Top
                };
            }
            else
            {
                PaperBackground.PanelOverride = null;
            }

            // Then the header:
            if (visuals.HeaderImagePath != null)
            {
                HeaderImage.TexturePath = visuals.HeaderImagePath;
                HeaderImage.MinSize = HeaderImage.TextureNormal?.Size ?? Vector2.Zero;
            }
            HeaderImage.ModulateSelfOverride = visuals.HeaderImageModulate;
            HeaderImage.Margin = new Thickness(visuals.HeaderMargin.Left, visuals.HeaderMargin.Top,
                visuals.HeaderMargin.Right, visuals.HeaderMargin.Bottom);

            // Then the footer
            if (visuals.FooterImagePath is { } path)
            {
                FooterImage.TexturePath = path.ToString();
                FooterImage.MinSize = FooterImage.TextureNormal?.Size ?? Vector2.Zero;
            }
            FooterImage.ModulateSelfOverride = visuals.FooterImageModulate;
            FooterImage.Margin = new Thickness(visuals.FooterMargin.Left, visuals.FooterMargin.Top,
                visuals.FooterMargin.Right, visuals.FooterMargin.Bottom);

            PaperContent.ModulateSelfOverride = visuals.ContentImageModulate;
            WrittenTextLabel.ModulateSelfOverride = visuals.FontAccentColor;
            FillStatus.ModulateSelfOverride = visuals.FontAccentColor;
            var contentImage = visuals.ContentImagePath != null ? _resCache.GetResource<TextureResource>(visuals.ContentImagePath) : null;

            if (contentImage != null)
            {
                // Setup the paper content texture, but keep a reference to it, as we can't set
                // some font-related properties here. We'll fix those up later, in Draw()
                _paperContentTex = new StyleBoxTexture
                {
                    Texture = contentImage,
                    Mode = StyleBoxTexture.StretchMode.Tile,
                };

                PaperContent.PanelOverride = _paperContentTex;
                _paperContentLineScale = visuals.ContentImageNumLines;
            }

            PaperContent.Margin = new Thickness(
                visuals.ContentMargin.Left, visuals.ContentMargin.Top,
                visuals.ContentMargin.Right, visuals.ContentMargin.Bottom);

            if (visuals.MaxWritableArea != null)
            {
                var a = (Vector2) visuals.MaxWritableArea;
                // Paper has requested that this has a maximum area that you can write on.
                // So, we'll make the window non-resizable and fix the size of the content.
                // Ideally, would like to be able to allow resizing only one direction.
                ScrollingContents.MinSize = Vector2.Zero;
                ScrollingContents.MinSize = a;

                if (a.X > 0.0f)
                {
                    ScrollingContents.MaxWidth = a.X;
                    _allowedResizeModes &= ~(DragMode.Left | DragMode.Right);
                    // Since this dimension has been specified by the user, we
                    // need to undo the SetSize which was configured in the xaml.
                    // Controls use NaNs to indicate unset for this value.
                    // This is leaky - there should be a method for this
                    SetWidth = float.NaN;
                }

                if (a.Y > 0.0f)
                {
                    ScrollingContents.MaxHeight = a.Y;
                    _allowedResizeModes &= ~(DragMode.Top | DragMode.Bottom);
                    SetHeight = float.NaN;
                }
            }
        }

        /// <summary>
        /// Control interface. We'll mostly rely on the children to do the drawing
        /// but in order to get lines on paper to match up with the rich text labels,
        /// we need to do a small calculation to sync them up.
        /// </summary>
        protected override void Draw(DrawingHandleScreen handle)
        {
            // Now do the deferred setup of the written area. At the point
            // that InitVisuals runs, the label hasn't had it's style initialized
            // so we need to get some info out now:
            if (WrittenTextLabel.TryGetStyleProperty<Font>("font", out var font))
            {
                float fontLineHeight = font.GetLineHeight(1.0f);

                // This positions the texture so the font baseline is on the bottom:
                _paperContentTex.ExpandMarginTop = font.GetDescent(UIScale);

                // And this scales the texture so that it's a single text line:
                var scaleY = (_paperContentLineScale * fontLineHeight) / _paperContentTex.Texture?.Height ?? fontLineHeight;
                _paperContentTex.TextureScale = new Vector2(1, scaleY);

                // Now, we might need to add some padding to the text to ensure
                // that, even if a header is specified, the text will line up with
                // where the content image expects the font to be rendered (i.e.,
                // adjusting the height of the header image shouldn't cause the
                // text to be offset from a line)
                {
                    var headerHeight = HeaderImage.Size.Y + HeaderImage.Margin.Top + HeaderImage.Margin.Bottom;
                    var headerInLines = headerHeight / (fontLineHeight * _paperContentLineScale);
                    var paddingRequiredInLines = (float) Math.Ceiling(headerInLines) - headerInLines;
                    var verticalMargin = fontLineHeight * paddingRequiredInLines * _paperContentLineScale;
                    TextAlignmentPadding.Margin = new Thickness(0.0f, verticalMargin, 0.0f, 0.0f);
                }
            }

            base.Draw(handle);
        }

        /// <summary>
        /// Initialize the paper contents, i.e. the text typed by the
        /// user and any stamps that have peen put on the page.
        /// </summary>
        public void Populate(PaperComponent.PaperBoundUserInterfaceState state)
        {
            bool isEditing = state.Mode == PaperComponent.PaperAction.Write;
            bool wasEditing = InputContainer.Visible;

            InputContainer.Visible = isEditing;
            EditButtons.Visible = isEditing;
            FormatToolbar.Visible = isEditing; // DS14

            var msg = new FormattedMessage();
            msg.AddMarkupPermissive(state.Text);

            // DS14-signatures-start
            var signatures = state.Signatures;
            var hasSignatures = signatures is { Count: > 0 };
            if (hasSignatures)
            {
                string signaturesLine;
                if (signatures.Count <= 2)
                {
                    if (signatures.Count == 1)
                        signaturesLine = $"{signatures[0]}";
                    else
                        signaturesLine = $"{signatures[0]} и {signatures[1]}";
                }
                else
                {
                    signaturesLine = string.Join(", ", signatures.Select(s => $"{s}"));
                }

                msg.AddMarkupPermissive($"\n\n[color=#4169E1][italic]{signaturesLine}[/italic][/color]");
            }
            // DS14-signatures-end

            // For premade documents, we want to be able to edit them rather than
            // replace them.
            var shouldCopyText = 0 == Input.TextLength && 0 != state.Text.Length;
            if (!wasEditing || shouldCopyText)
            {
                // We can get repeated messages with state.Mode == Write if another
                // player opens the UI for reading. In this case, don't update the
                // text input, as this player is currently writing new text and we
                // don't want to lose any text they already input.
                Input.TextRope = Rope.Leaf.Empty;
                Input.CursorPosition = new TextEdit.CursorPos();
                Input.InsertAtCursor(state.Text);
            }

            if (state.StampedBy.Count == 0) // DS14
                msg.AddMarkupPermissive("\r\n");

            // DS14-start
            WrittenTextLabel.SetMessage(msg, UserFormattableTags.BaseAllowedTags, DefaultTextColor);
            WrittenTextLabel.Visible = !isEditing && (state.Text.Length > 0 || hasSignatures); // DS14-signatures
            BlankPaperIndicator.Visible = !isEditing && state.Text.Length == 0 && !hasSignatures;
            // DS14-end

            StampDisplay.RemoveStamps();
            foreach (var stamper in state.StampedBy)
            {
                StampDisplay.AddStamp(new StampWidget { StampInfo = stamper });
            }

            StampDisplay.Visible = !isEditing && state.StampedBy.Count > 0; // DS14
        }

        /// <summary>
        /// BaseWindow interface. Allow users to drag UI around by grabbing
        /// anywhere on the page (like FancyWindow) but try to calculate
        /// reasonable dragging bounds because this UI can have round corners,
        /// and it can be hard to judge where to click to resize.
        /// </summary>
        protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        {
            var mode = DragMode.None;

            // Be quite generous with resize margins:
            if (relativeMousePos.Y < DRAG_MARGIN_SIZE)
            {
                mode |= DragMode.Top;
            }
            else if (relativeMousePos.Y > Size.Y - DRAG_MARGIN_SIZE)
            {
                mode |= DragMode.Bottom;
            }

            if (relativeMousePos.X < DRAG_MARGIN_SIZE)
            {
                mode |= DragMode.Left;
            }
            else if (relativeMousePos.X > Size.X - DRAG_MARGIN_SIZE)
            {
                mode |= DragMode.Right;
            }

            if ((mode & _allowedResizeModes) == DragMode.None)
            {
                return DragMode.Move;
            }

            return mode & _allowedResizeModes;
        }

        private void RunOnSaved()
        {
            // Prevent further saving while text processing still in
            SaveButton.Disabled = true;
            OnSaved?.Invoke(Rope.Collapse(Input.TextRope));
        }

        private void UpdateFillState()
        {
            if (MaxInputLength != -1)
            {
                var inputLength = Input.TextLength;
                FillStatus.Text = Loc.GetString("paper-ui-fill-level",
                    ("currentLength", inputLength),
                    ("maxLength", MaxInputLength));

                // Disable the save button if we've gone over the limit
                SaveButton.Disabled = inputLength > MaxInputLength;
            }
            else
            {
                FillStatus.Text = "";
                SaveButton.Disabled = false;
            }
        }
        
        // DS14-Start
        /// <summary>
        /// Wrap the current selection (or cursor) in a formatting tag pair. If the
        /// selection is already wrapped in exactly this pair, the tags are removed.
        /// </summary>
        private void ToggleInlineFormat(string openTag, string closeTag)
        {
            var text = Rope.Collapse(Input.TextRope);
            var lower = Input.SelectionLower.Index;
            var upper = Input.SelectionUpper.Index;
            var selected = text[lower..upper];
            var hadSelection = selected.Length > 0;

            string inner;
            var unwrapped = false;
            if (hadSelection &&
                selected.Length >= openTag.Length + closeTag.Length &&
                selected.StartsWith(openTag) &&
                selected.EndsWith(closeTag))
            {
                unwrapped = true;
                inner = selected[openTag.Length..^closeTag.Length];
            }
            else
            {
                inner = openTag + selected + closeTag;
            }

            var newText = text[..lower] + inner + text[upper..];

            if (hadSelection)
            {
                var start = unwrapped ? lower : lower + openTag.Length;
                var end = start + (unwrapped ? inner.Length : selected.Length);
                CommitTextChange(newText, end, start);
            }
            else
            {
                CommitTextChange(newText, lower + openTag.Length);
            }
        }

        /// <summary>
        /// Wrap every non-empty line of the current selection (or the current line)
        /// in a tag pair, toggling the tags off if all lines are already wrapped.
        /// </summary>
        private void ToggleBlockFormat(string openTag, string closeTag)
        {
            var text = Rope.Collapse(Input.TextRope);
            var lower = Input.SelectionLower.Index;
            var upper = Input.SelectionUpper.Index;

            ExpandSelectionToLines(text, ref lower, ref upper);

            var lines = text[lower..upper].Split('\n');
            var nonEmpty = lines.Where(static l => l.Length > 0).ToList();
            var allWrapped = nonEmpty.Count > 0 &&
                nonEmpty.All(l => l.StartsWith(openTag) && l.EndsWith(closeTag));

            var sb = new StringBuilder();
            if (allWrapped)
            {
                foreach (var line in lines)
                {
                    if (line.Length == 0)
                        continue;
                    sb.Append(line, openTag.Length, line.Length - openTag.Length - closeTag.Length);
                    sb.Append('\n');
                }
            }
            else
            {
                foreach (var line in lines)
                {
                    if (line.Length == 0)
                        continue;
                    sb.Append(openTag).Append(line).Append(closeTag).Append('\n');
                }
            }

            if (sb.Length == 0)
            {
                // The block only contains empty lines, insert empty tags for the user to type into.
                sb.Append(openTag).Append(closeTag);
            }
            else
            {
                sb.Remove(sb.Length - 1, 1);
            }

            var processed = sb.ToString();

            if (lines.All(static l => l.Length == 0))
            {
                CommitTextChange(text[..lower] + processed + text[upper..], lower + openTag.Length);
            }
            else
            {
                CommitTextChange(text[..lower] + processed + text[upper..], lower + processed.Length);
            }
        }

        /// <summary>
        /// Apply a heading level (1-3) to the whole lines of the selection. A null
        /// level removes heading tags from the affected lines.
        /// </summary>
        private void ApplyHeading(int? level)
        {
            var text = Rope.Collapse(Input.TextRope);
            var lower = Input.SelectionLower.Index;
            var upper = Input.SelectionUpper.Index;

            ExpandSelectionToLines(text, ref lower, ref upper);

            var lines = text[lower..upper].Split('\n');
            var sb = new StringBuilder();
            foreach (var line in lines)
            {
                if (line.Length == 0)
                    continue;
                sb.Append(ApplyHeadingToLine(line, level)).Append('\n');
            }

            if (sb.Length == 0)
            {
                if (level == null)
                    return;
                sb.Append($"[head={level}][/head]");
            }
            else
            {
                sb.Remove(sb.Length - 1, 1);
            }

            var processed = sb.ToString();

            if (lines.All(static l => l.Length == 0) && level != null)
            {
                CommitTextChange(text[..lower] + processed + text[upper..], lower + $"[head={level}]".Length);
            }
            else
            {
                CommitTextChange(text[..lower] + processed + text[upper..], lower + processed.Length);
            }
        }

        private static string ApplyHeadingToLine(string line, int? level)
        {
            var match = HeadingWrapRegex.Match(line);
            if (match.Success)
            {
                var content = match.Groups[1].Value;
                return level == null ? content : $"[head={level}]{content}[/head]";
            }

            return level == null ? line : $"[head={level}]{line}[/head]";
        }

        /// <summary>
        /// Called by the color picker on every slider/spinbox change. Only the swatch
        /// is updated live; the text is rewritten after the debounce timer expires.
        /// </summary>
        private void ApplyColor(Color color)
        {
            UpdateColorButton(color);

            _pendingColor = color;
            _hasPendingColor = true;
            _colorDebounceTimer = ColorApplyDelay;
        }

        /// <summary>
        /// Wrap the current selection in a color tag, replacing the color value of
        /// an already surrounding color tag.
        /// </summary>
        private void ApplyColorToText(Color color)
        {
            var hex = color.ToHexNoAlpha();

            var text = Rope.Collapse(Input.TextRope);
            var lower = Input.SelectionLower.Index;
            var upper = Input.SelectionUpper.Index;
            var selected = text[lower..upper];
            var hadSelection = selected.Length > 0;

            // Detect a directly surrounding [color=...]...[/color] tag.
            var openStart = -1;
            var openEnd = -1;
            if (hadSelection &&
                lower >= 8 &&
                upper + 7 <= text.Length &&
                text.Substring(upper, 7) == "[/color]")
            {
                var candidate = text.LastIndexOf("[color=", lower - 1, StringComparison.Ordinal);
                if (candidate != -1)
                {
                    var candidateEnd = text.IndexOf(']', candidate);
                    if (candidateEnd != -1 && candidateEnd + 1 == lower)
                    {
                        openStart = candidate;
                        openEnd = candidateEnd + 1;
                    }
                }
            }

            string newText;
            int cursorStart;
            int cursorEnd;
            if (openStart != -1)
            {
                // Replace only the color value of the surrounding tag.
                newText = text[..openStart] + $"[color={hex}]" + text[openEnd..];
                cursorStart = openStart + $"[color={hex}]".Length;
                cursorEnd = cursorStart + selected.Length;
            }
            else if (hadSelection)
            {
                newText = text[..lower] + $"[color={hex}]{selected}[/color]" + text[upper..];
                cursorStart = lower + $"[color={hex}]".Length;
                cursorEnd = cursorStart + selected.Length;
            }
            else
            {
                newText = text[..lower] + $"[color={hex}][/color]" + text[upper..];
                cursorStart = lower + $"[color={hex}]".Length;
                cursorEnd = cursorStart;
            }

            CommitTextChange(newText, cursorEnd, hadSelection ? cursorStart : null);
        }

        private void UpdateColorButton(Color color)
        {
            ColorButton.StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = color,
                BorderColor = Color.FromHex("#3b4e60"),
                BorderThickness = new Thickness(1),
            };
        }

        private void ToggleColorPicker()
        {
            if (_colorPickerWindow == null)
            {
                _colorPickerWindow = new DefaultWindow
                {
                    Title = Loc.GetString("paper-ui-toolbar-color"),
                    SetSize = new Vector2(320, 170),
                };

                var sliders = new ColorSelectorSliders
                {
                    SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv,
                    IsAlphaVisible = false,
                    HorizontalExpand = true,
                    VerticalExpand = true,
                    Margin = new Thickness(8),
                };
                sliders.OnColorChanged += ApplyColor;
                _colorPickerWindow.Contents.AddChild(sliders);
            }

            if (_colorPickerWindow.IsOpen)
                _colorPickerWindow.Close();
            else
                _colorPickerWindow.Open();
        }

        private void UpdatePreview()
        {
            if (!_previewMode)
                return;

            var msg = new FormattedMessage();
            msg.AddMarkupPermissive(Rope.Collapse(Input.TextRope));
            PreviewLabel.SetMessage(msg, UserFormattableTags.BaseAllowedTags, DefaultTextColor);
        }

        /// <summary>
        /// Expand the given range so that it covers whole lines of <paramref name="text"/>.
        /// A collapsed cursor is expanded to the single line under it.
        /// </summary>
        private static void ExpandSelectionToLines(string text, ref int lower, ref int upper)
        {
            if (lower == upper)
            {
                if (lower > 0 && text[lower - 1] != '\n')
                    lower = text.LastIndexOf('\n', lower - 1) + 1;
                var end = text.IndexOf('\n', lower);
                upper = end == -1 ? text.Length : end;
            }
            else
            {
                while (lower > 0 && text[lower - 1] != '\n')
                    lower--;
                while (upper < text.Length && text[upper] != '\n')
                    upper++;
            }
        }

        /// <summary>
        /// Replace the whole editor text, restore the cursor (and optionally a
        /// selection) and refresh all dependent UI.
        /// </summary>
        private void CommitTextChange(string newText, int cursorPos, int? selectionStart = null)
        {
            Input.TextRope = new Rope.Leaf(newText);
            // CursorPosition first: its setter collapses the selection.
            Input.CursorPosition = new TextEdit.CursorPos(cursorPos, TextEdit.LineBreakBias.Bottom);
            if (selectionStart != null)
            {
                Input.SelectionStart = new TextEdit.CursorPos(selectionStart.Value, TextEdit.LineBreakBias.Bottom);
            }

            UpdateFillState();
            UpdatePreview();

            if (!_previewMode)
                Input.GrabKeyboardFocus();
        }

        /// <summary>
        /// Fires the pending color change once the user has stopped dragging the
        /// color sliders for a moment.
        /// </summary>
        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            if (!_hasPendingColor)
                return;

            _colorDebounceTimer -= args.DeltaSeconds;
            if (_colorDebounceTimer <= 0)
            {
                _hasPendingColor = false;
                ApplyColorToText(_pendingColor);
            }
        }
        // DS14-End
    }
}
