using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Random;

namespace Content.Client.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class StampCollection : Container
{
    private List<StampWidget> _stamps = new();
    private readonly List<List<int>> _rows = new();

    /// Seed for random number generator to place stamps deterministically
    public int PlacementSeed;

    public StampCollection()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Remove any stamps from the page
    /// </summary>
    public void RemoveStamps()
    {
        _stamps.Clear();
        InvalidateArrange();
    }

    /// <summary>
    /// Adds a stamp to the display; will perform
    /// automatic layout.
    /// </summary>
    public void AddStamp(StampWidget s)
    {
        _stamps.Add(s);
        AddChild(s);
    }

    protected override Vector2 ArrangeOverride(Vector2 finalSize)
    {
        var random = new Random(PlacementSeed);
        // DS14-start
        var controlBox = new UIBox2(PixelSizeBox.TopLeft, PixelSizeBox.TopLeft + finalSize * UIScale);
        const float padding = 10.0f;
        const int maxColumns = 3;
        const float columnGap = 8.0f;
        const float rowGap = 8.0f;
        var availableWidth = MathF.Max(0.0f, controlBox.Width - padding * 2.0f);
        var availableHeight = MathF.Max(0.0f, controlBox.Height - padding * 2.0f);

        BuildRows(availableWidth, maxColumns, columnGap);

        var rowHeights = new float[_rows.Count];
        for (var row = 0; row < _rows.Count; row++)
        {
            foreach (var index in _rows[row])
            {
                rowHeights[row] = MathF.Max(rowHeights[row], _stamps[index].DesiredPixelSize.Y);
            }
        }

        var totalNaturalHeight = rowGap * Math.Max(0, _rows.Count - 1);
        foreach (var rowHeight in rowHeights)
        {
            totalNaturalHeight += rowHeight;
        }
        var rowScale = totalNaturalHeight <= 0.0f || totalNaturalHeight <= availableHeight
            ? 1.0f
            : availableHeight / totalNaturalHeight;

        var y = controlBox.Top + padding;

        for (var row = 0; row < _rows.Count; row++)
        {
            var rowIndices = _rows[row];
            var rowHeight = rowHeights[row] * rowScale;
            var rowWidth = -columnGap;
            foreach (var index in rowIndices)
            {
                rowWidth += _stamps[index].DesiredPixelSize.X + columnGap;
            }

            var x = controlBox.Left + padding + MathF.Max(0.0f, (availableWidth - rowWidth) * 0.5f);
            foreach (var index in rowIndices)
            {
                var stampOrientation = MathHelper.DegreesToRadians((random.NextFloat() - 0.5f) * 4.0f);
                _stamps[index].Orientation = stampOrientation;
                var jitter = new Vector2(
                    (random.NextFloat() - 0.5f) * 4.0f,
                    (random.NextFloat() - 0.5f) * 3.0f);
                var childCenter = new Vector2(
                    x + _stamps[index].DesiredPixelSize.X * 0.5f,
                    y + rowHeight * 0.5f) + jitter;

                var childHeLocal = _stamps[index].DesiredPixelSize * 0.5f;
                var c = childHeLocal * MathF.Abs(MathF.Cos(stampOrientation));
                var s = childHeLocal * MathF.Abs(MathF.Sin(stampOrientation));
                var childHePage = new Vector2(c.X + s.Y, s.X + c.Y);
                var clampedCenter = Clamp(Shrink(controlBox, childHePage), childCenter);
                var finalPosition = clampedCenter - childHePage;
                var finalPositionAsInt = new Vector2i((int)finalPosition.X, (int)finalPosition.Y);
                _stamps[index].ArrangePixel(new UIBox2i(finalPositionAsInt, finalPositionAsInt + _stamps[index].DesiredPixelSize));

                x += _stamps[index].DesiredPixelSize.X + columnGap;
            }

            y += rowHeight + rowGap * rowScale;
        }
        // DS14-end
        return finalSize;
    }

    // DS14-start
    private void BuildRows(float availableWidth, int maxColumns, float columnGap)
    {
        _rows.Clear();

        for (var i = 0; i < _stamps.Count; i++)
        {
            if (_rows.Count == 0 || !CanFit(_rows[^1], i, availableWidth, maxColumns, columnGap))
                _rows.Add(new List<int>());

            _rows[^1].Add(i);
        }
    }

    private bool CanFit(List<int> row, int stampIndex, float availableWidth, int maxColumns, float columnGap)
    {
        if (row.Count >= maxColumns)
            return false;

        var width = (float) _stamps[stampIndex].DesiredPixelSize.X;
        foreach (var index in row)
        {
            width += _stamps[index].DesiredPixelSize.X + columnGap;
        }

        return width <= availableWidth;
    }
    // DS14-end

    /// <summary>
    /// Shrink a UIBox2 by a half extents, moving both the top-left and
    /// bottom-right closer together.
    /// </summary>
    private UIBox2 Shrink(UIBox2 box, Vector2 shrinkHe)
    {
        return new UIBox2(box.TopLeft + shrinkHe, box.BottomRight - shrinkHe);
    }

    /// <summary>
    /// Returns the input vector clamped to be within the UIBox
    /// </summary>
    private Vector2 Clamp(UIBox2 box, Vector2 point)
    {
        return Vector2.Min(box.BottomRight, Vector2.Max(box.TopLeft, point));
    }
}

