using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Client.Verbs.UI;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using System.Linq;
using Robust.Shared.Localization;
using Content.Shared.Strip.Components;
using Robust.Shared.GameObjects;

namespace Content.Client.Inventory;

public sealed partial class AcceptStipInputInterface : FancyWindow
{
    public AcceptStipInputInterface(StartStripInsertInventoryMessage message)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // XML formatting
        AnswerCallButton.AddStyleClass("ButtonAccept");
        EndCallButton.AddStyleClass("Caution");
        AnswerCallButton.Text = Loc.GetString("strippable-bound-user-interface-inserting-menu-yes-answer", ("item", message.Held));
        EndCallButton.Text = Loc.GetString("strippable-bound-user-interface-inserting-menu-no-answer", ("item", message.Held));

        MessegeText.Text = Loc.GetString("strippable-bound-user-interface-inserting-menu-message", ("user", message.Name), ("item", message.Held));
    }
}
