//Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Client.UserInterface.Controls;
using Content.Shared.Strip.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Inventory;

[GenerateTypedNameReferences]
public sealed partial class AcceptStripInputInterface : FancyWindow
{
    private const int MessageLineLength = 52;
    private const int ButtonLineLength = 28;

    public event Action<bool>? Answered;

    public AcceptStripInputInterface(StartStripInsertInventoryMessage message)
    {
        RobustXamlLoader.Load(this);

        var cache = IoCManager.Resolve<IResourceCache>();
        var smallFont = new VectorFont(cache.GetResource<FontResource>("/Fonts/NotoSansDisplay/NotoSansDisplay-Regular.ttf"), 11);
        MessageText.FontOverride = smallFont;
        AnswerCallText.FontOverride = smallFont;
        EndCallText.FontOverride = smallFont;

        var acceptText = Loc.GetString("strippable-bound-user-interface-inserting-menu-yes-answer", ("item", message.Held));
        var rejectText = Loc.GetString("strippable-bound-user-interface-inserting-menu-no-answer", ("item", message.Held));

        AnswerCallText.Text = WrapText(acceptText, ButtonLineLength);
        AnswerCallButton.ToolTip = acceptText;
        EndCallText.Text = WrapText(rejectText, ButtonLineLength);
        EndCallButton.ToolTip = rejectText;

        var messageText = Loc.GetString("strippable-bound-user-interface-inserting-menu-message", ("user", message.Name), ("item", message.Held));
        MessageText.Text = WrapText(messageText, MessageLineLength);
        MessageText.ToolTip = messageText;

        AnswerCallButton.OnPressed += _ => Answered?.Invoke(true);
        EndCallButton.OnPressed += _ => Answered?.Invoke(false);
    }

    private static string WrapText(string text, int lineLength)
    {
        var words = text.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (words.Length <= 1)
            return text;

        var lines = new List<string>();
        var currentLine = words[0];

        for (var i = 1; i < words.Length; i++)
        {
            var word = words[i];
            if (currentLine.Length + word.Length + 1 <= lineLength)
            {
                currentLine += " " + word;
                continue;
            }

            lines.Add(currentLine);
            currentLine = word;
        }

        lines.Add(currentLine);
        return string.Join('\n', lines);
    }
}
