//Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Client.UserInterface.Controls;
using Content.Shared.Strip.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Inventory;

[GenerateTypedNameReferences]
public sealed partial class AcceptStripInputInterface : FancyWindow
{
    public event Action<bool>? Answered;

    public AcceptStripInputInterface(StartStripInsertInventoryMessage message)
    {
        RobustXamlLoader.Load(this);

        AnswerCallButton.AddStyleClass("ButtonAccept");
        EndCallButton.AddStyleClass("Caution");

        var acceptText = Loc.GetString("strippable-bound-user-interface-inserting-menu-yes-answer", ("item", message.Held));
        var rejectText = Loc.GetString("strippable-bound-user-interface-inserting-menu-no-answer", ("item", message.Held));

        AnswerCallButton.Text = acceptText;
        AnswerCallButton.ToolTip = acceptText;
        EndCallButton.Text = rejectText;
        EndCallButton.ToolTip = rejectText;

        var messageText = Loc.GetString("strippable-bound-user-interface-inserting-menu-message", ("user", message.Name), ("item", message.Held));
        MessageText.Text = messageText;
        MessageText.ToolTip = messageText;

        AnswerCallButton.OnPressed += _ => Answered?.Invoke(true);
        EndCallButton.OnPressed += _ => Answered?.Invoke(false);
    }
}
